### ISSUE TITLE
Bwa-Meth

### ISSUE THREAD

**Issue by lmanchon** [smithlabcode/methpipe#101]
-Hi,

is it possible to use first Bwa-Meth (https://github.com/brentp/bwa-meth) or ERNE-BS5 (https://sourceforge.net/projects/erne/) and then use to-mr in methpipe process ?

thank you --

**Comment by pawatmwit** [comment]
I did this exact thing (BWA-meth -> to-mr) and it worked great!

**Comment by cviner** [comment]
I too have gotten this to work well, via `to-mr -m 'general' <SAM/BAM file>`.

Please refer to the [resolved issue](https://github.com/smithlabcode/methpipe/issues/70) discussing this, for details.
