### ISSUE TITLE
RADmeth -1

### ISSUE THREAD

**Issue by malvarez227** [smithlabcode/methpipe#105]
Hi!

For some of my loci, I get P values of -1. Any ideas what that might represent?

Thanks!

**Comment by bdecato** [comment]
Hi Mariano,

Thanks for using methpipe.  A p-value of -1 from radmeth means that the test was not performed for that CpG site. It could mean one of two things:

1) There is no coverage for all samples in either/both the case and control sets
2) The methylation level is identical across all samples

In both cases, the regression would fail. It looks like this is only documented in a comment in the RADMeth code: I'll add it to the manual.  In the future please try and ask questions via our google group forum (https://groups.google.com/forum/#!forum/methpipe); it is better indexed by google for others with the same question.

Thanks for pointing this out!!

Ben
