### ISSUE TITLE
column meanings of regression output

### ISSUE THREAD

**Issue by lxcfuji** [smithlabcode/methpipe#107]
In your pipeline manual, page 13, "combing significance and adjusting for multiple testing" section, the description of output bed file is "the last four column corresponds to the **methylated/unmethylated** read counts of the case group and control group". 
However, based on previous experience, the column meaning should be:
**total**/methylated reads of the case and control group.
I know you recently made an updated version (methpipe-3.4.3), so just want to verify which of the above descriptions hold true? 
Thank you in advance

**Comment by bdecato** [comment]
Hi @lxcfuji,

You are correct that the last four columns represent the **total** and **number of methylated observations** for the case and control group. The latest release did not fix this inaccuracy in the manual. I have updated the manual. Thank you!

Ben
