### ISSUE TITLE
Trouble calculating allelic-specific methylation scores

### ISSUE THREAD

**Issue by dingailuma** [smithlabcode/methpipe#109]
[mydata.mr.zip](https://github.com/smithlabcode/methpipe/files/1316032/mydata.mr.zip)

Hi,
When I ran the command line 
`allelicmeth -c hg19.fa -o mydata.allelicmeth mydata.mr`
it always came out the error that 
```
could not convert:
chr16	1097776	1097777	1	0	0	0	0	0	0	+
```
Does anyone know why this trouble happened and how can I fix it ? Thank you very much for your help !
I think the mr file I used was correct as no error came out when I called DMR by methpipe with the same file.

**Comment by mengzhou** [comment]
The input of allelicmeth should be epiread format. Please see the
corresponding section in the manual for converting mr format to epiread.


Best regards,
Meng

**Comment by dingailuma** [comment]
Hi memgzhou,
![screen shot 2017-09-19 at 18 38 05](https://user-images.githubusercontent.com/24386332/30618748-c5513ffa-9d69-11e7-8cc8-118760cfa707.png)
Here is what written in your user manual.
I think calling Allelically methylated regions (AMRs) need input as epiread format. Is that right ?

**Comment by mengzhou** [comment]
It seems you are reading a different version of methpipe manual. Can you
check the latest one? Now Section 3.3.1 is the introduction of epiread
format as the input of allelic-specific methylation analysis.


Best regards,
Meng

**Comment by dingailuma** [comment]
OK . thank you then .
