### ISSUE TITLE
HIV LTR for methpipe

### ISSUE THREAD

**Issue by antoine4ucsd** [smithlabcode/methpipe#110]
Hi
I am performing exploratory analyses on the HIV LTR regions.
While the sequencing has a lot of room for improvement, I was able to map the (short) reads to the bisulfite conversion of the reference using the standard params of Bowtie2 and the GUI software UGENE...
The link below contains the bam output from the raw fq files and from the trimmed fq files mapped to the ref.
Next I created the mr file with the following:
`/to-mr -s 0 -o UGENE_C1bowtie2.mr -m general UGENE_C1bowtie2.sam.bam_sorted.bam LC_ALL=C sort -k 1,1 -k 2,2n -k 3,3n -k 6,6`
It seems to work properly.
Although I sorted the bam file, I have the following error ('not properly sorted') while running the duplicate remover:

`duplicate-remover -S UGENE_C1bowtie2_stat.txt -o UGENE_C1bowtie2.mr.drmove UGENE_C1bowtie2.mr 
input not properly sorted`

I tried to move on for the bsrate but I am not sure how to deal with non-human genome ref:
I execute the following where ref is the name of my reference and ./reference is a folder containing the ref (previously processed with makedb):

`bsrate –c ./reference –N –o UGENE_C1bowtie2.mr.bsrate UGENE_C1bowtie2.mr 
required argument missing: [-c, -chrom]`
or

`bsrate –c ref –N –o UGENE_C1bowtie2.mr.bsrate UGENE_C1bowtie2.mr 
required argument missing: [-c, -chrom]`

Would you have any advice?
any chance that any R package can read through my input data although they were not processed with bismark? 

thanks again in advance for your advices.

https://www.dropbox.com/sh/m01rkcu8mzv4nz4/AABIR6vsl53xm_KQsbbtHNA-a?dl=0

**Comment by bdecato** [comment]
Hi Antoine.

Thanks for using methpipe. After running `to-mr`, did you sort your mapped read file using the command on page four of the methpipe manual? If you sort your mapped read file, you should be able to remove duplicate reads with no issues.

For your issue with `bsrate`, could you please try appending a .fa suffix to your reference file? The usage statement of the program specifies that this is non-optional.

For your last question, I am not sure what you mean. An R package to read through my input data and do what? At least for the analysis in methpipe, a mapped-read format file and later, methcounts file is sufficient.

Ben

**Comment by antoine4ucsd** [comment]
thanks Benjamin!
I will take a second look asap and keep you posted

a

**Comment by antoine4ucsd** [comment]
sorry for being not very efficient but the bsrate command is still not working...
`/bsrate -c ./reference/ref.fa –o UGENE_C1bowtie2.mr.bsrate UGENE_C1bowtie2.mr`
It does not seem to accept the -c argument. I am probably missing something obvious.
(regarding the sorting, is methpipe using samtools?)
the command line is the one below, right?
`LC_ALL=C sort -k 1,1 -k 2,2n -k 3,3n -k 6,6 \
-o Human_ESC.mr.sorted_start Human_ESC.mr`

thanks in advance for your help
