### ISSUE TITLE
NULL values when converting SAM --> MR format

### ISSUE THREAD

**Issue by iiiir** [smithlabcode/methpipe#111]
Hi,

I used walt to do the alignment and then the sam is converted to mr using to-mr:
$ to-mr -m general chrM.sam -o chrM.mr

however,  got some "NULL" lines. 
can you advice what is happening here?thanks

![capture](https://user-images.githubusercontent.com/4137873/30947807-ccdc36fa-a3d9-11e7-9b11-4a947a8c8675.PNG)

**Comment by andrewdavidsmith** [comment]
Can anyone confirm if this is still happening?
