### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by hmyh1202** [smithlabcode/methpipe#113]
Hi:
   what any other software can do SNP calling, ASM and LD analysis for BS data, especially based on bismark alignment output?

**Comment by bdecato** [comment]
Hi @hmyh1202,

Thanks for using our pipeline. In the future, we try to keep github issues for problems or feature suggestions specific to methpipe.

methpipe has programs dedicated to analysis of allele-specific methylation: first, convert the BAM format output from bismark to mapped reads by using `to-mr`, and then run `methstates` for epiread format. From there you can use `allelicmeth` and `amrfinder` to analyze specific site probabilities of ASM and discovery of allelicly methylated regions.

For more specific instructions, please consult the manual.

Thanks again for using our stuff!

**Comment by hmyh1202** [comment]
OK, thank U so much!
