### ISSUE TITLE
Question for method of ASM calling

### ISSUE THREAD

**Issue by hmyh1202** [smithlabcode/methpipe#114]
Dear sir：

   Can you explain the algorithm of ASM with no SNP information？ And what analysis can I do in downstream research?

The Best!

**Comment by bdecato** [comment]
Hi again,

Take a look at the original paper for amrfinder:

http://www.pnas.org/content/109/19/7332.abstract

Briefly, the idea is to scan the genome with a sliding window and for each region, fit two models: a one-allele model and a two-allele model. In the one-allele model, the reads and the methylation state of the CpGs on them are not organized into any particular pattern. In the two-allele model, it is possible to partition reads overlapping several CpG sites into an unmethylated group and a methylated group in roughly 50/50 proportion.

After fitting, you have likelihoods for each model and can do a likelihood ratio test to determine whether the two-allele model fits significantly better than the one-allele model. At the end of the program, adjacent two-allele model bins are combined into "allelicly methylated regions."

For future questions about methpipe, please submit them to the google group and avoid posting on the github (https://groups.google.com/forum/#!forum/methpipe).

Thanks!!

Ben
