### ISSUE TITLE
duplicate-remover stats fix

### ISSUE THREAD

**Issue by mengzhou** [smithlabcode/methpipe#132]
1. Change `duplication_rate` to `unique_fraction`, which indicates the fraction of reads that do not have any duplications. This should be `(reads_out - reads_with_duplicates)/(reads_in)`.
2. Change `duplication_rate_for_dups` to `duplication_rate`, with a new definition describing the average number of duplicates per read. It is `(reads_removed + reads_with_duplicates)/reads_with_duplicates`.

A script is also needed for merging multiple dup_stat files.

**Comment by andrewdavidsmith** [comment]
Fixed by @mengzhou
