### ISSUE TITLE
struct Site in merge-methcounts.cpp

### ISSUE THREAD

**Issue by masarunakajima** [smithlabcode/methpipe#133]
I noticed that `merge-methcounts.cpp` has a struct called Site. I also noticed that programs such as `levels.cpp` use struct MSite that is defined in `MethpipeSite.hpp`. I think we should use MSite in `merge-methcounts.cpp` for uniformity.

**Comment by andrewdavidsmith** [comment]
This has been replaced with the recent updates to `merge-methcounts` so the redundant struct is removed.
