### ISSUE TITLE
Read gzip compressed .sam or .mr files for input

### ISSUE THREAD

**Issue by enormandeau** [smithlabcode/methpipe#135]
We have a few undergoing and planned bisulfite sequencing projects. These projects have a few hundred samples for species with gigabase+ size genomes. We found that Walt performed really well for the mapping but the fact that methpipe cannot use compressed input, for example `.mr.gz` files, is leading to huge demands in terms of disk space. Namely, as our first two projects are only started, we are already using 3-4 TB of disk space.

It would be a fantastic feature of methpipe if it could read gzip compressed input files (.sam.gz or .bam and .mr.gz). This would translate directly into multiple TB of saved disk space and thousands of research dollars freed from the need to buy this disk space.

We do not have anybody to modify the C++ code but we would be happy to assist in testing any such modification (on `.mr.gz` in our case).

**Comment by andrewdavidsmith** [comment]
I think this works now @enormandeau for most of the tools. Sorry it took so long, but I hope we can get more feedback from you in the future.

**Comment by enormandeau** [comment]
Thanks for this update. I think this should be very useful for all methpipe users. I don't know if I will personally have to use WALT / methpipe but when students / postdocs use it I will make sure they use 4.0.0
