### ISSUE TITLE
merge-methcounts producing massive file size is normal?

### ISSUE THREAD

**Issue by Surajuvm** [smithlabcode/methpipe#137]
Hello,

I am trying to use CGmap file produced from BSseeker2 pipeline to generate proportion table for differential methylation. I formatted the CGmap file to match the meth counts file. My meth counts file looks like this 
```
NC_006853_1     94      +       CG      0.01    1133
NC_006853_1     95      -       CG      0.01    1478
NC_006853_1     111     +       CG      0.01    1219
NC_006853_1     112     -       CG      0.02    1518
NC_006853_1     299     +       CG      0.01    1362
NC_006853_1     300     -       CG      0.01    2058
NC_006853_1     346     +       CG      0.01    1223
NC_006853_1     347     -       CG      0.05    1559
NC_006853_1     363     +       CG      0.0     126
NC_006853_1     364     -       CG      0.03    699
```
I have ten such meth counts file which I want to merge in the proportion table. Each of these files are of size (0.5 - 0.8) gbs. I used the `merge-methcounts` function of `methpipe-3.4.3`. The job has been running for over six days and the size of the proportion table is ~2500 gbs. 

Is it normal to have proportion table this huge? Any insight would be really appreciated. 

Thank you,
Suraj

**Comment by bdecato** [comment]
Hi Suraj,

Can you confirm the command you're using to output the proportion table?
And can you try with the -t (tabular) option if you have not already?

Thanks,

Ben


On Wed, May 22, 2019 at 2:30 PM Surajuvm <notifications@github.com> wrote:

> Hello,
>
> I am trying to use CGmap file produced from BSseeker2 pipeline to generate
> proportion table for differential methylation. I formatted the CGmap file
> to match the meth counts file. My meth counts file looks like this
>
> NC_006853_1     94      +       CG      0.01    1133
> NC_006853_1     95      -       CG      0.01    1478
> NC_006853_1     111     +       CG      0.01    1219
> NC_006853_1     112     -       CG      0.02    1518
> NC_006853_1     299     +       CG      0.01    1362
> NC_006853_1     300     -       CG      0.01    2058
> NC_006853_1     346     +       CG      0.01    1223
> NC_006853_1     347     -       CG      0.05    1559
> NC_006853_1     363     +       CG      0.0     126
> NC_006853_1     364     -       CG      0.03    699
>
> I have ten such meth counts file which I want to merge in the proportion
> table. Each of these files are of size (0.5 - 0.8) gbs. I used the
> merge-methcounts function of methpipe-3.4.3. The job has been running for
> over six days and the size of the proportion table is ~2500 gbs.
>
> Is it normal to have proportion table this huge? Any insight would be
> really appreciated.
>
> Thank you,
> Suraj
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_smithlabcode_methpipe_issues_137-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DABYF5UDT33JCQA3QYEV5T7TPWWGKNA5CNFSM4HOW4HNKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GVI7LMA&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=SpXCeWczJOWPYEneTspxwg&m=MWh9Bc3xvGMNfqYAsxkVqm1lkqyNyt3sZxEG0jfUnjo&s=cDgCpbZ6ztdCkhauxGP46ZVaGzm9O9LxOCx3vdxeevs&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABYF5UFJIVO75S4D6QRJ5QTPWWGKNANCNFSM4HOW4HNA&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=SpXCeWczJOWPYEneTspxwg&m=MWh9Bc3xvGMNfqYAsxkVqm1lkqyNyt3sZxEG0jfUnjo&s=y6EMRM2XACvL72qhA-YWSg6t-jEZHHpg9GQQ7RyOy7g&e=>
> .
>


-- 
-- 
Benjamin Decato, Ph.D.
Computational Biology Section,
Department of Biological Sciences,
University of Southern California
1050 Childs Way, RRI 408M
Los Angeles, CA 90089-2910

**Comment by Surajuvm** [comment]
Hello Ben, 

The command I used is 

```
/merge-methcounts -t control_1117IL.meth control_1376IL.meth control_3403IL.meth control_6528IL.meth control_8664IL.meth \ case_1180IL.meth case_5144IL.meth case_5678IL.meth case_8156IL.meth case_9154IL.meth > ProportionTable_IL.txt
```
I used the -t option. 

Thanks.

**Comment by andrewdavidsmith** [comment]
This might happen if the sites in different files are interpreted as being different sites. @Surajuvm Can you head several of the files so we can look at the first 3 columns to ensure they are corresponding? Those are the ones that `merge-methcounts` uses to determine which rows should be merged and which ones should be kept separate. Similarly, please indicate the result of running head on the output (or partial output) file.

**Comment by Surajuvm** [comment]
Sure, these are the head of a different meth count files. 
```
[sbhatta4@bluemoon-user1 IL]$ head case_1180IL.meth
NC_006853_1     94      +       CG      0.01    1133
NC_006853_1     95      -       CG      0.01    1478
NC_006853_1     111     +       CG      0.01    1219
NC_006853_1     112     -       CG      0.02    1518
NC_006853_1     299     +       CG      0.01    1362
NC_006853_1     300     -       CG      0.01    2058
NC_006853_1     346     +       CG      0.01    1223
NC_006853_1     347     -       CG      0.05    1559
NC_006853_1     363     +       CG      0.0     126
NC_006853_1     364     -       CG      0.03    699
```
```
[sbhatta4@bluemoon-user1 IL]$ head case_5144IL.meth
NC_006853_1     94      +       CG      0.0     1506
NC_006853_1     95      -       CG      0.0     2313
NC_006853_1     111     +       CG      0.0     1655
NC_006853_1     112     -       CG      0.01    2406
NC_006853_1     299     +       CG      0.01    2146
NC_006853_1     300     -       CG      0.01    3070
NC_006853_1     346     +       CG      0.01    1948
NC_006853_1     347     -       CG      0.03    2282
NC_006853_1     363     +       CG      0.01    1766
NC_006853_1     364     -       CG      0.04    1541
```
```
[sbhatta4@bluemoon-user1 IL]$ head control_1117IL.meth
NC_006853_1     94      +       CG      0.0     1279
NC_006853_1     95      -       CG      0.01    1874
NC_006853_1     111     +       CG      0.0     1390
NC_006853_1     112     -       CG      0.01    1950
NC_006853_1     299     +       CG      0.01    1674
NC_006853_1     300     -       CG      0.01    2638
NC_006853_1     346     +       CG      0.01    1549
NC_006853_1     347     -       CG      0.03    1889
NC_006853_1     363     +       CG      0.01    1394
NC_006853_1     364     -       CG      0.03    1255
```
```
[sbhatta4@bluemoon-user1 IL]$ head control_1376IL.meth
NC_006853_1     94      +       CG      0.01    1543
NC_006853_1     95      -       CG      0.0     2476
NC_006853_1     111     +       CG      0.0     1690
NC_006853_1     112     -       CG      0.01    2626
NC_006853_1     299     +       CG      0.01    1991
NC_006853_1     300     -       CG      0.01    3044
NC_006853_1     346     +       CG      0.01    1895
NC_006853_1     347     -       CG      0.03    2404
NC_006853_1     363     +       CG      0.01    156
NC_006853_1     364     -       CG      0.03    1304

```
Here is the head of the output file.

```
[sbhatta4@bluemoon-user1 IL]$ head ProportionTable_IL.txt
control_1117IL  control_1376IL  control_3403IL  control_6528IL  control_8664IL   case_1180IL    case_5144IL     case_5678IL     case_8156IL     case_9154IL
NC_006853_1:94:+:CG     1279    0       1543    15      1285    13      1337    13      1142    11      0       0       1506    0       1074    0       948 0
        663     0
NC_006853_1:95:-:CG     1874    19      2476    0       2028    20      1870    19      1768    0       0       0       2313    0       1661    0       132013       1061    11
NC_006853_1:111:+:CG    1390    0       1690    0       1396    14      1469    15      1230    12      0       0       1655    0       1154    12      103310       713     0
NC_006853_1:112:-:CG    1950    20      2626    26      2127    21      2045    20      1866    19      0       0       2406    24      1798    18      140214       1149    0
NC_006853_1:299:+:CG    1674    17      1991    20      1722    17      1398    14      1571    16      0       0       2146    21      1247    12      12360
        943     9
NC_006853_1:300:-:CG    2638    26      3044    30      2722    27      2024    20      2177    22      0       0       3070    31      1689    0       183118       1334    13
NC_006853_1:346:+:CG    1549    15      1895    19      1579    0       1276    13      1420    0       0       0       1948    19      1124    11      11640
        838     17
NC_006853_1:347:-:CG    1889    57      2404    72      1950    98      1583    47      1570    79      0       0       2282    68      1295    39      134940       969     29
NC_006853_1:363:+:CG    1394    14      156     2       164     0       120     0       1164    0       0       0       1766    18      120     0       98  0
        741     0
```

To me, the files seem to be in proper order. 

I talked to one of my colleagues about this problem, whom I know used Radmeth pipeline for her wgbs analysis. She said she had a similar problem while generating the proportion table when she used methpipe-3.4.3. However, when she used methpipe-3.4.2 for a different reason, then the merge-methcounts worked fine. I wonder if other people had this issue. To me, it looks like something is going on `in loop` over and over. 

I hope this helps. 

Thank you.

**Comment by andrewdavidsmith** [comment]
Thanks very much for this info @Surajuvm. Can you email me directly about this?
