### ISSUE TITLE
[Cleanup TwoStatHMM.*pp] Function declarations include non-const, non-reference primitive types?

### ISSUE THREAD

**Issue by andrewdavidsmith** [smithlabcode/methpipe#138]
@xjlizji @bdecato @mengzhou Does anyone know why certain functions (e.g. `TransitionPosteriors`) in the TwoStateHMM and related classes have parameters that are declared as `double` but without the `const` or without a reference? These seem like they don't need to change inside the functions, at least in one example I looked at. So I'm not sure why they are declared the way they are.

**Comment by mengzhou** [comment]
Looks like they were defined as they are from the very beginning, like this one:
https://github.com/smithlabcode/methpipe/blame/master/src/common/TwoStateHMM.cpp#L736

**Comment by andrewdavidsmith** [comment]
Can one of you fix this? Also, there is an instance variable `emission_correction_count` and rename the class from `TwoStateHMMB` to `TwoStateHMM`, which also means changing a couple lines in `hmr.cpp`?

**Comment by andrewdavidsmith** [comment]
@xjlizji Did you take care of this?

**Comment by xjlizji** [comment]
I fixed the const variable types and removed `emission_correction_count`. Do you mean we should change all `TwoStateHMMB` to `TwoStateHMM`? Just want to make sure.

**Comment by andrewdavidsmith** [comment]
Yes. I think there is no reason to avoid using the `TwoStateHMM` and I can't even remember why there was a `B` version made at this point.

**Comment by xjlizji** [comment]
Maybe for "Baum-Welch". Now all `TwoStateHMMB` are changed to `TwoStateHMM`
