### ISSUE TITLE
hmr rep passing vectors by const value?

### ISSUE THREAD

**Issue by andrewdavidsmith** [smithlabcode/methpipe#141]
Is there a reason why these are passed by const value instead of reference?
```C++
  void
  PosteriorScores_rep(const std::vector<std::vector<std::pair<double, double> > > &values,
                      const std::vector<size_t> &reset_points,
                      const std::vector<double> &start_trans,
                      const std::vector<std::vector<double> > &trans,
                      const std::vector<double> &end_trans,
                      const std::vector<double> fg_alpha,
                      const std::vector<double> fg_beta,
                      const std::vector<double> bg_alpha,
                      const std::vector<double> bg_beta,
                      const bool &fg_class,
                      std::vector<double> &llr_scores) const;
```

**Comment by andrewdavidsmith** [comment]
Looks like these are not usually large vectors, as they are emission parameters, but I think they should be references.

**Comment by andrewdavidsmith** [comment]
These instances should be identified and corrected. For non-primitive types the source code in `TwoStateHMM.*pp` files only involves large enough objects that they should all be passed as references when they are const.

**Comment by sarvarip** [comment]
Solved by @andrewdavidsmith (https://github.com/smithlabcode/methpipe/commit/b4abae159f5d9430c869fe76cd55c8f618be1fdd)
