### ISSUE TITLE
merge-methcounts split the same sites into different rows

### ISSUE THREAD

**Issue by yongchao** [smithlabcode/methpipe#142]
Hi

When I used the command the merge-methcounts, the same cytosine sites will appear in two different rows. This has been tested in two different computers and the most recent github and the the most release version 3.4.3

The following command used the attached toydata to reproduce the bug.
As you can see from the result file prop_table.txt,  The four sites ( KL568509.1:2238:+:CpG        KL568509.1:2244:+:CpG     KL568509.1:2248:+:CpG   KL568509.1:2259:+:CpG) have appeared twice. In more complicated datasets, the same site may appear as many as 32 times. 

merge-methcounts -t Undetermined_L1.meth.txt Undetermined_L2.meth.txt  -o prop_table.txt

[prop_table.txt](https://github.com/smithlabcode/methpipe/files/3342461/prop_table.txt)
[Undetermined_L1.meth.txt](https://github.com/smithlabcode/methpipe/files/3342462/Undetermined_L1.meth.txt)
[Undetermined_L2.meth.txt](https://github.com/smithlabcode/methpipe/files/3342463/Undetermined_L2.meth.txt)

**Comment by andrewdavidsmith** [comment]
@yongchao Thanks for pointing this out. I know the problem, and we will update the source. I will update merge-methcounts to check that the input files are properly sorted. In the meantime, if you do something like `sort -k 1,1 -k 2,2g -k 3,3` on your methcounts files before attempting the merge, it will probably work. I tried that on your toy data set, and it worked. Thanks for reporting this!

**Comment by yongchao** [comment]
The input data has already been sorted by `sort -k1,1 -k2,2n`. Your sort command doesn't change the input file anyhow. I tried your sort command and ran the merge-counts in the new files and it still had the same bug.

**Comment by yongchao** [comment]
@andrewdavidsmith Look forward to your update on the code.

**Comment by andrewdavidsmith** [comment]
Try checking the sorting locale. Make sure it’s as specified in the manual.

**Comment by yongchao** [comment]
I now recompile the program after "export LC_ALL=C" and "export LANG=C"  to make sure the code was recompiled under the same locale. and also these same two settings (LC_ALL and LANG) to run sort and other commands.

Now the problem is gone. Thanks for pointing the locale setting.

**Comment by andrewdavidsmith** [comment]
@yongchao Can you confirm that recompiling the code was necessary? And not that sorting with the right locale was sufficient? I don't want to give incorrect advice on this issue.

**Comment by andrewdavidsmith** [comment]
@sarvarip Can you please look at this code and see if you think it will solve the issue:
```

**Comment by yongchao** [comment]
@andrewdavidsmith I  recompiled the code under the problematic locale "en_US.UTF-8" and  I can confirm that sorting with locale "C" is sufficient. 

I was a little bit of paranoid earlier as I have already been bitten by the locale setting for a couple of times for other software (requiring setting both LC_ALL and LANG to C). In linux environment, most software is happy with locale C. The setting of C locale is now in my .bashrc file of all my computers to avoid any surprise.

**Comment by andrewdavidsmith** [comment]
@yongchao Thanks very much -- that's helpful info!

**Comment by yongchao** [comment]
Based on the whole thread

I will replace the message 

`throw runtime_error("error: sites not sorted in " + filenames[i]);`

to 

`throw runtime_error("error: sites not sorted in " + filenames[i]+"\n please sort it by \" LC_ALL=C sort -k1,1 -k2,2g -k3,3\"");`
