### ISSUE TITLE
Unsynchronized update of parameters

### ISSUE THREAD

**Issue by xjlizji** [smithlabcode/methpipe#143]
The emission parameters are updated in `single_iteration`:
```
  vector<double> posteriors;
  get_posteriors(forward, backward, posteriors);
  fg_distro.fit(vals_a, vals_b, posteriors);

  one_minus(begin(posteriors), end(posteriors), begin(posteriors));
  bg_distro.fit(vals_a, vals_b, posteriors);
```
But the transition parameters are updated outside `single_iteration` after
a convergence check:
```
    converged = (get_delta(prev_total, total) < tolerance);

    if (converged) {
      if (VERBOSE)
        cerr << "CONVERGED" << endl;
    }
    else {
      p_fb = p_fb_est;
      p_bf = p_bf_est;
      prev_total = total;
    }
```
So when the converging condition is met, emission parameters will still
get updated while transition parameters are kept same to the previous iteration.

**Comment by terencewtli** [comment]
we could move the entire emission re-estimation inside single_iteration to the else statement after convergence check?

**Comment by andrewdavidsmith** [comment]
Closing as likely no longer relevant.
