### ISSUE TITLE
methdiff output format: inconsistency between coverage and methylated read counts

### ISSUE THREAD

**Issue by akmorrow13** [smithlabcode/methpipe#145]
The [methpipe manual](http://smithlabresearch.org/downloads/methpipe-manual.pdf) on page 11 states the methdiff columns. The columns include the coverage and the methylated read counts for a given sample. However, in the example, the methylated counts can be greater than the coverage. I have also noticed after running on my own data the coverage can be 0, but the number of methylated reads is > 0. How is this possible?

**Comment by mengzhou** [comment]
Thanks for catching this. I can confirm that the four columns after the probability are: A_meth_reads, A_unmeth_reads, B_meth_reads, B_unmeth_reads (see codes https://github.com/smithlabcode/methpipe/blob/master/src/radmeth/methdiff.cpp#L89). The manual is not correct.
@terencewtli can you help updating the manual?

**Comment by terencewtli** [comment]
I'll get to it today!

**Comment by akmorrow13** [comment]
Thanks @terencewtli and @mengzhou, that makes a lot more sense!

**Comment by terencewtli** [comment]
Hi @akmorrow13! We are working on changing the Methpipe manual on our website because that one is outdated. The manual in this repository is our most updated one and has the change that @mengzhou was talking about - for now, please refer to that one (located in docs). Thanks again for the feedback!

**Comment by terencewtli** [comment]
The methpipe manual on smithlabresearch.org has now been updated to the most recent one with the updated descriptions of the methdiff columns.
