### ISSUE TITLE
Reading in symmetric CpGs into hmr 

### ISSUE THREAD

**Issue by tsengale** [smithlabcode/methpipe#146]
When reading in symmetric CpGs into hmr, if any line contains a non-symmetric CpG, the program should fail gracefully.

**Comment by terencewtli** [comment]
Hi, thank you for bringing this up! I am working on this right now and will get back to you.

**Comment by terencewtli** [comment]
We have updated the code to report an error if there are non-symmetric CpGs. Please pull our code for the new update. Thanks for your feedback!
