### ISSUE TITLE
to-mr program for bsmap

### ISSUE THREAD

**Issue by fitart** [smithlabcode/methpipe#147]
Hello, I tried to convert .bam file (from bsmap) into .mr using 'to-mr' command from both Major release 4.0.0 and methpipe-3.4.3, so I replaced the following command with my file name.
$ to-mr -o Human_NHFF.mr -m bsmap Human_NHFF.bam

However, it returned the following message.
"bsmap no longer supported [use general]" 

According to the user manual, it should work. I am wondering if bsmap can be supported. Thanks,

**Comment by mengzhou** [comment]
Hi, thanks for using methpipe. We decided to integrate the support for bsmap with "general" because of some format incompatibility. Please use `to-mr -m general` with your file and see if it works fine.
