### ISSUE TITLE
tar.gz file 

### ISSUE THREAD

**Issue by lauzikaite** [smithlabcode/methpipe#150]
Hi!

The link for the latest stable release tar.gz file provided in the README is not taking me anywhere... Would you be able to provide a working link for that? Since the version on the http://smithlabresearch.org/software/methpipe/ website is only 3.4.3.

Similarly, I cannot find a link to the tar.gz file for the `smithlab_cpp` library.

Thank you in advance for your reply.

**Comment by terencewtli** [comment]
Hi! Here's the link to our most recent release, 4.0.0.
https://github.com/smithlabcode/methpipe/issues/150

This is the link to the most recent smithlab_cpp release. 
https://github.com/smithlabcode/smithlab_cpp/releases

**Comment by lauzikaite** [comment]
Thanks!
