### ISSUE TITLE
Where is headers within libsmithlab_cpp-1.0.2?

### ISSUE THREAD

**Issue by aganve** [smithlabcode/methpipe#151]
Hello,

I am at this step of installing methpipe
`$ ../configure --prefix=/some/reasonable/place \
    CPPFLAGS='-I /path/to/smithlab_cpp/headers' \
    LDFLAGS='-L/path/to/smithlab_cpp/lib'`

but do not see a directory where the smithlab_cpp headers can be found. I see `lib` but no `headers`

Therefore, I get the following error: 

Failed to locate smithlab_cpp on your system. Please use the LDFLAGS
and CPPFLAGS variables to specify the directories where the
smithlab_cpp library and headers can be found.

Help would be appreciated.

**Comment by guilhermesena1** [comment]
Hi aganve,

thank you for the message, this definitely does seem like an improvement for readme is necessary. Compiling smithlab_cpp should not generate a headers directory, and if you install it to some outside directory, the cpps and hpps should be inside the include directory. Does replacing `headers` with `include` in your `configure` command work successfully?
