### ISSUE TITLE
Methylation level calculation for PMD

### ISSUE THREAD

**Issue by juheon** [smithlabcode/methpipe#152]
I want to make sure how the methylation level of each bin is calculated for PMDs.
According to the manual, "The program calculates in nonoverlapping bins the total methylated and unmethylated read counts.".
Does it mean "Total number of methylated reads in each bin" / "Total number of reads in each bin"?
Or, do you calculate the methylation level of each CpG and calculates the mean of all CpGs in each bin?

**Comment by bdecato** [comment]
Hi Juheon,

It's the total number of methylated reads in each bin divided by the total coverage of the bin.

Thanks,

Ben

**Comment by juheon** [comment]
Thank you!
