### ISSUE TITLE
methcounts reporting no reads for a chrom when chroms are missing

### ISSUE THREAD

**Issue by andrewdavidsmith** [smithlabcode/methpipe#153]
When chromosomes are missing, it seems like `methcounts` is reporting that there are no reads for the next chromosome that has reads. For example, after processing reads for chr10, and when chr10_GL383545v1_alt is among the mapped reads, but not in the fasta genome file, it will be reported that there are no reads for chr11, when the correct message is that chr10_GL383545v1_alt cannot be found.

**Comment by masarunakajima** [comment]
If no one is working on this issue, I would like to look into it.

**Comment by guilhermesena1** [comment]
this was fixed on the SAM pre release which will be merged, so closing it for now
