### ISSUE TITLE
Incomplete files

### ISSUE THREAD

**Issue by surak** [smithlabcode/methpipe#154]
The https://github.com/smithlabcode/methpipe/releases/download/v4.1.1/methpipe-4.1.1.tar.gz is complete, but the other files on the same link are missing the recursive parts: here: https://github.com/smithlabcode/methpipe/releases

**Comment by andrewdavidsmith** [comment]
@surak We are aware of those, we don't like them, and will try to get rid of them in the future. But for now, they will appear when we make a release. GitHub auto-generates them from the tagged commit associated with a release. Again, we will keep looking for other work-arounds, but please ignore them and only use the "release" (which is numbered) and not the auto-archived source (which is not).
