### ISSUE TITLE
bsrate_sam takes a long time if input has random chrom distribution

### ISSUE THREAD

**Issue by guilhermesena1** [smithlabcode/methpipe#156]
bsrate should fail if it sees two non-continuous chromosomes as it will take a very long time to finish processing if reads are not grouped by chromosome

**Comment by guilhermesena1** [comment]
fixed with 37a6f01ea8279c394507c0e24b98718778b886b7

**Comment by mengzhou** [comment]
How about checking for an index file? For BAM you can only index it after sorting, so requiring for an index automatically ensures sorting. I know you are working on SAM, just a thought.

**Comment by andrewdavidsmith** [comment]
I think the original idea is still the easiest, and probably the only one that will always work -- just specify sorted order is required and report a failure if not. I don't think any other way will work, unless it requires more constraints on the users. This is how most versions have functioned.
