### ISSUE TITLE
format_reads too slow

### ISSUE THREAD

**Issue by andrewdavidsmith** [smithlabcode/methpipe#157]
The code for `format_reads` was not written to be fast, but right now it's taking way too long. Part of it might have to do with the sequential searching done (repeatedly) to locate certain optional tags in each record. Other issues might be related to using the cigar repeatedly to extract information about positions within the reference. This needs to be faster.

**Comment by guilhermesena1** [comment]
this was also fixed on the SAM_pre_release, should be fine when we integrate the new `sam_rec` class that does not check for the validity of SAM entries
