### ISSUE TITLE
Problem when running methcounts, pmd, etc!

### ISSUE THREAD

**Issue by bobia9991** [smithlabcode/methpipe#161]
Hi SmithLab team!
I downloaded Test data, at http://smithlabresearch.org/software/methpipe/
After installed methpipe, I tested with downloaded data but had problems when running commands, such as methcounts; pmd; etc 

**1. methcounts
methcounts  -o $rs/binh1.meth -c $gen/ -v $rs/snippet_uniq.mr
n_chrom_files: 1
n_chroms: 1
bad line in MappedRead file: chr22	29971	30072	FREDDYKRUEGER_0001:1:26:268:1868#0/2	0	-	AGGTTTAAGGTTTTTAAAATAGTTGATATTTTTAAATTGGTTTTTTTGTATATTAAATTAAAGAAATTAGGTTTTTAAATTAAGGAAAATGAATGATAGTTe_ab_adg_ggggagec]c]_ab^bageggggggggggbggggfgggggegbggggegfgggggffegfggggggggebefdgggggeegggggffebggg**

**2. pmd
pmd  -o Human_ColonCancer-chr19.pmd -v -i 15 Human_ColonCancer-chr19.meth 
[DYNAMICALLY SELECTING BIN SIZE]
evaluating bin size 1000
ERROR:	bad methpipe site line: "chr19	60118	60119	CpG:0	0	+"**

MacOS Catalina, 10.15.6.
Terminal: zsh shell, 5.8 (x86_64-apple-darwin19.3.0)

Please, help me to resolve those issues. Thank you!

**Comment by xxzzwan** [comment]
Same with you. I also used MacOS Catalina. But after using linux system, there's no such problem. Maybe it's a system version issue!

**Comment by guilhermesena1** [comment]
there seems to be a serious issue with mac IO and we will look into it to make sure we will circumvent this issue

**Comment by andrewdavidsmith** [comment]
@guilhermesena1 has this issue been addressed in a subsequent version?

**Comment by guilhermesena1** [comment]
yes I removed the rdbuf line on every class and every program which solved the problem on methpipe 5.0.0
