### ISSUE TITLE
expected class-name before ‘(’ token    SMITHLABException

### ISSUE THREAD

**Issue by Myskiper** [smithlabcode/methpipe#163]
I want to install version 4.1.1, but get error

 CXX      GenomicRegion.lo
In file included from ../../../src/smithlab_cpp/GenomicRegion.hpp:27:0,
                 from ../../../src/smithlab_cpp/GenomicRegion.cpp:23:
../../../src/smithlab_cpp/smithlab_utils.hpp:296:54: error：expected class-name before ‘{’ token
 struct SMITHLABException : public std::runtime_error {
                                                      ^
../../../src/smithlab_cpp/smithlab_utils.hpp: ‘SMITHLABException::SMITHLABException(std::string)’中:
../../../src/smithlab_cpp/smithlab_utils.hpp:297:56: error：expected class-name before ‘(’ token
   SMITHLABException(std::string m) : std::runtime_error(m), message(m) {}
                                                        ^
../../../src/smithlab_cpp/smithlab_utils.hpp:297:56: error：expected ‘{’ before ‘(’ token
make[3]: *** [GenomicRegion.lo] error 1

**Comment by andrewdavidsmith** [comment]
Can you confirm the version of your compiler, by providing the output to `g++ --version`?

**Comment by Myskiper** [comment]
> Can you confirm the version of your compiler, by providing the output to `g++ --version`?

I use the conmand configure CXX=/share/app/gcc-4.9.3/bin/gcc, So the version of gcc is 4.9.3;

**Comment by terencewtli** [comment]
Hi - could you try installing methpipe with a newer version of gcc (5.x.x)?

**Comment by andrewdavidsmith** [comment]
@Myskiper But `CXX` is supposed to point to a C++ compiler, and anything that looks like `bin/gcc` is probably a C compiler. The variable used in Makefiles for a C compiler is `CC`.

**Comment by Myskiper** [comment]
Thanks,I change the GCC to 5.2.0, install successful!
