### ISSUE TITLE
Unable to make & make install

### ISSUE THREAD

**Issue by hchetia** [smithlabcode/methpipe#164]
Hi,
I am trying to install methpipe in linux.
I am successfully through the configure steps. At the make step, I get the following error-

make  all-recursive
make[1]: Entering directory `/rugpfs/fs0/hntz_lab/scratch/hchetia/softwares/methpipe-4.1.1/build'
Making all in src/smithlab_cpp
make[2]: Entering directory `/rugpfs/fs0/hntz_lab/scratch/hchetia/softwares/methpipe-4.1.1/build/src/smithlab_cpp'
make  all-am
make[3]: Entering directory `/rugpfs/fs0/hntz_lab/scratch/hchetia/softwares/methpipe-4.1.1/build/src/smithlab_cpp'
  CXX      OptionParser.lo
../../../src/smithlab_cpp/OptionParser.cpp: In function ‘void read_config_file(const string&, std::vector<std::basic_string<char> >&)’:
../../../src/smithlab_cpp/OptionParser.cpp:371:54: error: no matching function for call to ‘regex_replace(std::string&, std::regex, const char [1])’
     line = regex_replace(line, regex(outer_space), "");
                                                      ^
../../../src/smithlab_cpp/OptionParser.cpp:371:54: note: candidates are:
In file included from /usr/include/c++/4.8.2/regex:62:0,
                 from ../../../src/smithlab_cpp/OptionParser.cpp:35:
/usr/include/c++/4.8.2/bits/regex.h:2182:5: note: template<class _Rx_traits, class _Ch_type> std::basic_string<_Ch_type> std::regex_replace(const std::basic_string<_Ch_type>&, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
     regex_replace(const basic_string<_Ch_type>& __s,
     ^
/usr/include/c++/4.8.2/bits/regex.h:2182:5: note:   template argument deduction/substitution failed:
../../../src/smithlab_cpp/OptionParser.cpp:371:54: note:   mismatched types ‘const std::basic_string<_Ch_type>’ and ‘const char [1]’
     line = regex_replace(line, regex(outer_space), "");
                                                      ^
In file included from /usr/include/c++/4.8.2/regex:62:0,
                 from ../../../src/smithlab_cpp/OptionParser.cpp:35:
/usr/include/c++/4.8.2/bits/regex.h:2162:5: note: template<class _Out_iter, class _Bi_iter, class _Rx_traits, class _Ch_type> _Out_iter std::regex_replace(_Out_iter, _Bi_iter, _Bi_iter, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
     regex_replace(_Out_iter __out, _Bi_iter __first, _Bi_iter __last,
     ^
/usr/include/c++/4.8.2/bits/regex.h:2162:5: note:   template argument deduction/substitution failed:
../../../src/smithlab_cpp/OptionParser.cpp:371:54: note:   deduced conflicting types for parameter ‘_Bi_iter’ (‘std::basic_regex<char>’ and ‘const char*’)
     line = regex_replace(line, regex(outer_space), "");
                                                      ^
../../../src/smithlab_cpp/OptionParser.cpp:372:55: error: no matching function for call to ‘regex_replace(std::string&, std::regex, const char [2])’
     line = regex_replace(line, regex(inner_space), " ");
                                                       ^
../../../src/smithlab_cpp/OptionParser.cpp:372:55: note: candidates are:
In file included from /usr/include/c++/4.8.2/regex:62:0,
                 from ../../../src/smithlab_cpp/OptionParser.cpp:35:
/usr/include/c++/4.8.2/bits/regex.h:2182:5: note: template<class _Rx_traits, class _Ch_type> std::basic_string<_Ch_type> std::regex_replace(const std::basic_string<_Ch_type>&, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
     regex_replace(const basic_string<_Ch_type>& __s,
     ^
/usr/include/c++/4.8.2/bits/regex.h:2182:5: note:   template argument deduction/substitution failed:
../../../src/smithlab_cpp/OptionParser.cpp:372:55: note:   mismatched types ‘const std::basic_string<_Ch_type>’ and ‘const char [2]’
     line = regex_replace(line, regex(inner_space), " ");
                                                       ^
In file included from /usr/include/c++/4.8.2/regex:62:0,
                 from ../../../src/smithlab_cpp/OptionParser.cpp:35:
/usr/include/c++/4.8.2/bits/regex.h:2162:5: note: template<class _Out_iter, class _Bi_iter, class _Rx_traits, class _Ch_type> _Out_iter std::regex_replace(_Out_iter, _Bi_iter, _Bi_iter, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
     regex_replace(_Out_iter __out, _Bi_iter __first, _Bi_iter __last,
     ^
/usr/include/c++/4.8.2/bits/regex.h:2162:5: note:   template argument deduction/substitution failed:
../../../src/smithlab_cpp/OptionParser.cpp:372:55: note:   deduced conflicting types for parameter ‘_Bi_iter’ (‘std::basic_regex<char>’ and ‘const char*’)
     line = regex_replace(line, regex(inner_space), " ");
                                                       ^
../../../src/smithlab_cpp/OptionParser.cpp:389:64: error: no matching function for call to ‘regex_replace(std::string&, std::regex, const char [1])’
       option_value = regex_replace(line, regex(outer_space), "");
                                                                ^
../../../src/smithlab_cpp/OptionParser.cpp:389:64: note: candidates are:
In file included from /usr/include/c++/4.8.2/regex:62:0,
                 from ../../../src/smithlab_cpp/OptionParser.cpp:35:
/usr/include/c++/4.8.2/bits/regex.h:2182:5: note: template<class _Rx_traits, class _Ch_type> std::basic_string<_Ch_type> std::regex_replace(const std::basic_string<_Ch_type>&, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
     regex_replace(const basic_string<_Ch_type>& __s,
     ^
/usr/include/c++/4.8.2/bits/regex.h:2182:5: note:   template argument deduction/substitution failed:
../../../src/smithlab_cpp/OptionParser.cpp:389:64: note:   mismatched types ‘const std::basic_string<_Ch_type>’ and ‘const char [1]’
       option_value = regex_replace(line, regex(outer_space), "");
                                                                ^
In file included from /usr/include/c++/4.8.2/regex:62:0,
                 from ../../../src/smithlab_cpp/OptionParser.cpp:35:
/usr/include/c++/4.8.2/bits/regex.h:2162:5: note: template<class _Out_iter, class _Bi_iter, class _Rx_traits, class _Ch_type> _Out_iter std::regex_replace(_Out_iter, _Bi_iter, _Bi_iter, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
     regex_replace(_Out_iter __out, _Bi_iter __first, _Bi_iter __last,
     ^
/usr/include/c++/4.8.2/bits/regex.h:2162:5: note:   template argument deduction/substitution failed:
../../../src/smithlab_cpp/OptionParser.cpp:389:64: note:   deduced conflicting types for parameter ‘_Bi_iter’ (‘std::basic_regex<char>’ and ‘const char*’)
       option_value = regex_replace(line, regex(outer_space), "");
                                                                ^
make[3]: *** [OptionParser.lo] Error 1
make[3]: Leaving directory `/rugpfs/fs0/hntz_lab/scratch/hchetia/softwares/methpipe-4.1.1/build/src/smithlab_cpp'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/rugpfs/fs0/hntz_lab/scratch/hchetia/softwares/methpipe-4.1.1/build/src/smithlab_cpp'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/rugpfs/fs0/hntz_lab/scratch/hchetia/softwares/methpipe-4.1.1/build'
make: *** [all] Error 2

**Comment by terencewtli** [comment]
Hi, this looks like it might be a compiler version issue. Can you post the output of `g++ --version`?

**Comment by andrewdavidsmith** [comment]
Looks like maybe it's from gcc 4.8.2. I'm not sure if c++11 is supported in that version, which would cause the problem for `regex`

**Comment by hchetia** [comment]
Hi
The gcc version  is 4.9.4.

**Comment by andrewdavidsmith** [comment]
Any chance you can directly show the output as requested above for g++? Also, there is 4.8.2 in the paths your compiler is trying to use to locate standard c++ headers (as shown in the error output). We use c++, not c, so if there is a discrepancy we need info on the g++ directly.

**Comment by hchetia** [comment]
![image](https://user-images.githubusercontent.com/64626735/93392883-8cf95500-f83f-11ea-81eb-4023f1c5845e.png)
is this okay?

**Comment by hchetia** [comment]
I am unsure why the compiler being used in 4.8.2!

**Comment by andrewdavidsmith** [comment]
Yes. Thanks. We will see if we can figure out why you got that problem.

**Comment by hchetia** [comment]
Thanks andrew.

**Comment by hchetia** [comment]
Hi I was wondering if you had an update on my issue. Thanks.

**Comment by hchetia** [comment]
Hi I am using a Centos 6 system. 
g++ -std=c++11 -o regex_test regex_test.cpp command failed to run. Sharing the output with this comment.
nohup.out

**Comment by terencewtli** [comment]
Hi! Sorry for the late response - I'm not sure why the include headers and your compiler version are different, but I believe the issue ultimately boils down to your version of gcc not supporting the regex elements in our code. I am able to compile `methpipe` with 5.1.1 but unable to when I switch to gcc 4.8.1. Could you try running `make` on our code after switching to a newer version of gcc (maybe start with 5.x.x)?

**Comment by andrewdavidsmith** [comment]
I think the conclusion here is the compiler is just too old, it’s really too old to be supporting anymore anyway.

**Comment by hchetia** [comment]
Hi, 
I noticed that this issue was closed.
Just adding that I was able to build he program easily on my Mac OSX Catalina which uses gcc version 4.2.1.
Yet building it on the Centos OS that uses 4.8.1 somehow failed.

**Comment by PhrenoVermouth** [comment]
Hi Andrew, my configure seems fine but got stuck on the make step (really a disaster). I'm using the devtoolset in CentOS to switch to GCC7, which was shown below:

```
[root@kanglab build]# g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/opt/rh/devtoolset-7/root/usr --mandir=/opt/rh/devtoolset-7/root/usr/share/man --infodir=/opt/rh/devtoolset-7/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --enable-plugin --with-linker-hash-style=gnu --enable-initfini-array --with-default-libstdcxx-abi=gcc4-compatible --with-isl=/builddir/build/BUILD/gcc-7.3.1-20180303/obj-x86_64-redhat-linux/isl-install --enable-libmpx --enable-gnu-indirect-function --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC)

[root@kanglab build]# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/opt/rh/devtoolset-7/root/usr --mandir=/opt/rh/devtoolset-7/root/usr/share/man --infodir=/opt/rh/devtoolset-7/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --enable-plugin --with-linker-hash-style=gnu --enable-initfini-array --with-default-libstdcxx-abi=gcc4-compatible --with-isl=/builddir/build/BUILD/gcc-7.3.1-20180303/obj-x86_64-redhat-linux/isl-install --enable-libmpx --enable-gnu-indirect-function --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC)
```
and for other Required libraries I used yum to install properly:
```
 root@kanglab  ~  rpm -a -q  | grep htslib                                                                           ✔  ⚡  2781  15:05:19
htslib-devel-1.9-5.el7.x86_64
htslib-1.9-5.el7.x86_64
 root@kanglab  ~  rpm -a -q  | grep gsl-devel                                                                        ✔  ⚡  2782  15:05:28
gsl-devel-1.15-13.el7.x86_64
```
My error seems related to Htslib? I'm really bewildered:
```
[root@kanglab build]# make
make  all-recursive
make[1]: Entering directory `/root/methpipe-5.0.0/build'
Making all in src/smithlab_cpp
make[2]: Entering directory `/root/methpipe-5.0.0/build/src/smithlab_cpp'
make  all-am
make[3]: Entering directory `/root/methpipe-5.0.0/build/src/smithlab_cpp'
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../../../src/smithlab_cpp     -O3 -MT GenomicRegion.o -MD -MP -MF .deps/GenomicRegion.Tpo -c -o GenomicRegion.o ../../../src/smithlab_cpp/GenomicRegion.cpp
mv -f .deps/GenomicRegion.Tpo .deps/GenomicRegion.Po
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../../../src/smithlab_cpp     -O3 -MT MappedRead.o -MD -MP -MF .deps/MappedRead.Tpo -c -o MappedRead.o ../../../src/smithlab_cpp/MappedRead.cpp
mv -f .deps/MappedRead.Tpo .deps/MappedRead.Po
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../../../src/smithlab_cpp     -O3 -MT OptionParser.o -MD -MP -MF .deps/OptionParser.Tpo -c -o OptionParser.o ../../../src/smithlab_cpp/OptionParser.cpp
mv -f .deps/OptionParser.Tpo .deps/OptionParser.Po
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../../../src/smithlab_cpp     -O3 -MT QualityScore.o -MD -MP -MF .deps/QualityScore.Tpo -c -o QualityScore.o ../../../src/smithlab_cpp/QualityScore.cpp
mv -f .deps/QualityScore.Tpo .deps/QualityScore.Po
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../../../src/smithlab_cpp     -O3 -MT bisulfite_utils.o -MD -MP -MF .deps/bisulfite_utils.Tpo -c -o bisulfite_utils.o ../../../src/smithlab_cpp/bisulfite_utils.cpp
mv -f .deps/bisulfite_utils.Tpo .deps/bisulfite_utils.Po
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../../../src/smithlab_cpp     -O3 -MT chromosome_utils.o -MD -MP -MF .deps/chromosome_utils.Tpo -c -o chromosome_utils.o ../../../src/smithlab_cpp/chromosome_utils.cpp
mv -f .deps/chromosome_utils.Tpo .deps/chromosome_utils.Po
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../../../src/smithlab_cpp     -O3 -MT sim_utils.o -MD -MP -MF .deps/sim_utils.Tpo -c -o sim_utils.o ../../../src/smithlab_cpp/sim_utils.cpp
mv -f .deps/sim_utils.Tpo .deps/sim_utils.Po
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../../../src/smithlab_cpp     -O3 -MT smithlab_os.o -MD -MP -MF .deps/smithlab_os.Tpo -c -o smithlab_os.o ../../../src/smithlab_cpp/smithlab_os.cpp
mv -f .deps/smithlab_os.Tpo .deps/smithlab_os.Po
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../../../src/smithlab_cpp     -O3 -MT smithlab_utils.o -MD -MP -MF .deps/smithlab_utils.Tpo -c -o smithlab_utils.o ../../../src/smithlab_cpp/smithlab_utils.cpp
mv -f .deps/smithlab_utils.Tpo .deps/smithlab_utils.Po
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../../../src/smithlab_cpp     -O3 -MT zlib_wrapper.o -MD -MP -MF .deps/zlib_wrapper.Tpo -c -o zlib_wrapper.o ../../../src/smithlab_cpp/zlib_wrapper.cpp
mv -f .deps/zlib_wrapper.Tpo .deps/zlib_wrapper.Po
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../../../src/smithlab_cpp     -O3 -MT dna_four_bit.o -MD -MP -MF .deps/dna_four_bit.Tpo -c -o dna_four_bit.o ../../../src/smithlab_cpp/dna_four_bit.cpp
mv -f .deps/dna_four_bit.Tpo .deps/dna_four_bit.Po
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../../../src/smithlab_cpp     -O3 -MT cigar_utils.o -MD -MP -MF .deps/cigar_utils.Tpo -c -o cigar_utils.o ../../../src/smithlab_cpp/cigar_utils.cpp
mv -f .deps/cigar_utils.Tpo .deps/cigar_utils.Po
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../../../src/smithlab_cpp     -O3 -MT sam_record.o -MD -MP -MF .deps/sam_record.Tpo -c -o sam_record.o ../../../src/smithlab_cpp/sam_record.cpp
mv -f .deps/sam_record.Tpo .deps/sam_record.Po
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../../../src/smithlab_cpp     -O3 -MT htslib_wrapper_deprecated.o -MD -MP -MF .deps/htslib_wrapper_deprecated.Tpo -c -o htslib_wrapper_deprecated.o ../../../src/smithlab_cpp/htslib_wrapper_deprecated.cpp
mv -f .deps/htslib_wrapper_deprecated.Tpo .deps/htslib_wrapper_deprecated.Po
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../../../src/smithlab_cpp     -O3 -MT htslib_wrapper.o -MD -MP -MF .deps/htslib_wrapper.Tpo -c -o htslib_wrapper.o ../../../src/smithlab_cpp/htslib_wrapper.cpp
mv -f .deps/htslib_wrapper.Tpo .deps/htslib_wrapper.Po
rm -f libsmithlab_cpp.a
ar cru libsmithlab_cpp.a GenomicRegion.o MappedRead.o OptionParser.o QualityScore.o bisulfite_utils.o chromosome_utils.o sim_utils.o smithlab_os.o smithlab_utils.o zlib_wrapper.o dna_four_bit.o cigar_utils.o sam_record.o htslib_wrapper_deprecated.o htslib_wrapper.o
ranlib libsmithlab_cpp.a
make[3]: Leaving directory `/root/methpipe-5.0.0/build/src/smithlab_cpp'
make[2]: Leaving directory `/root/methpipe-5.0.0/build/src/smithlab_cpp'
make[2]: Entering directory `/root/methpipe-5.0.0/build'
source='../src/analysis/pmd.cpp' object='src/analysis/pmd.o' libtool=no \
DEPDIR=.deps depmode=none /bin/sh ../depcomp \
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I..  -I ../src/common -I ../src/smithlab_cpp   -O3  -c -o src/analysis/pmd.o ../src/analysis/pmd.cpp
source='../src/common/BetaBin.cpp' object='src/common/BetaBin.o' libtool=no \
DEPDIR=.deps depmode=none /bin/sh ../depcomp \
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I..  -I ../src/common -I ../src/smithlab_cpp   -O3  -c -o src/common/BetaBin.o ../src/common/BetaBin.cpp
source='../src/common/Distro.cpp' object='src/common/Distro.o' libtool=no \
DEPDIR=.deps depmode=none /bin/sh ../depcomp \
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I..  -I ../src/common -I ../src/smithlab_cpp   -O3  -c -o src/common/Distro.o ../src/common/Distro.cpp
source='../src/common/EmissionDistribution.cpp' object='src/common/EmissionDistribution.o' libtool=no \
DEPDIR=.deps depmode=none /bin/sh ../depcomp \
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I..  -I ../src/common -I ../src/smithlab_cpp   -O3  -c -o src/common/EmissionDistribution.o ../src/common/EmissionDistribution.cpp
source='../src/common/Epiread.cpp' object='src/common/Epiread.o' libtool=no \
DEPDIR=.deps depmode=none /bin/sh ../depcomp \
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I..  -I ../src/common -I ../src/smithlab_cpp   -O3  -c -o src/common/Epiread.o ../src/common/Epiread.cpp
source='../src/common/EpireadStats.cpp' object='src/common/EpireadStats.o' libtool=no \
DEPDIR=.deps depmode=none /bin/sh ../depcomp \
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I..  -I ../src/common -I ../src/smithlab_cpp   -O3  -c -o src/common/EpireadStats.o ../src/common/EpireadStats.cpp
source='../src/common/LevelsCounter.cpp' object='src/common/LevelsCounter.o' libtool=no \
DEPDIR=.deps depmode=none /bin/sh ../depcomp \
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I..  -I ../src/common -I ../src/smithlab_cpp   -O3  -c -o src/common/LevelsCounter.o ../src/common/LevelsCounter.cpp
source='../src/common/MethpipeSite.cpp' object='src/common/MethpipeSite.o' libtool=no \
DEPDIR=.deps depmode=none /bin/sh ../depcomp \
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I..  -I ../src/common -I ../src/smithlab_cpp   -O3  -c -o src/common/MethpipeSite.o ../src/common/MethpipeSite.cpp
source='../src/common/Smoothing.cpp' object='src/common/Smoothing.o' libtool=no \
DEPDIR=.deps depmode=none /bin/sh ../depcomp \
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I..  -I ../src/common -I ../src/smithlab_cpp   -O3  -c -o src/common/Smoothing.o ../src/common/Smoothing.cpp
source='../src/common/ThreeStateHMM.cpp' object='src/common/ThreeStateHMM.o' libtool=no \
DEPDIR=.deps depmode=none /bin/sh ../depcomp \
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I..  -I ../src/common -I ../src/smithlab_cpp   -O3  -c -o src/common/ThreeStateHMM.o ../src/common/ThreeStateHMM.cpp
source='../src/common/TwoStateHMM.cpp' object='src/common/TwoStateHMM.o' libtool=no \
DEPDIR=.deps depmode=none /bin/sh ../depcomp \
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I..  -I ../src/common -I ../src/smithlab_cpp   -O3  -c -o src/common/TwoStateHMM.o ../src/common/TwoStateHMM.cpp
source='../src/common/TwoStateHMM_PMD.cpp' object='src/common/TwoStateHMM_PMD.o' libtool=no \
DEPDIR=.deps depmode=none /bin/sh ../depcomp \
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I..  -I ../src/common -I ../src/smithlab_cpp   -O3  -c -o src/common/TwoStateHMM_PMD.o ../src/common/TwoStateHMM_PMD.cpp
source='../src/common/bsutils.cpp' object='src/common/bsutils.o' libtool=no \
DEPDIR=.deps depmode=none /bin/sh ../depcomp \
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I..  -I ../src/common -I ../src/smithlab_cpp   -O3  -c -o src/common/bsutils.o ../src/common/bsutils.cpp
source='../src/common/numerical_utils.cpp' object='src/common/numerical_utils.o' libtool=no \
DEPDIR=.deps depmode=none /bin/sh ../depcomp \
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I..  -I ../src/common -I ../src/smithlab_cpp   -O3  -c -o src/common/numerical_utils.o ../src/common/numerical_utils.cpp
rm -f libmethpipe.a
ar cru libmethpipe.a src/common/BetaBin.o src/common/Distro.o src/common/EmissionDistribution.o src/common/Epiread.o src/common/EpireadStats.o src/common/LevelsCounter.o src/common/MethpipeSite.o src/common/Smoothing.o src/common/ThreeStateHMM.o src/common/TwoStateHMM.o src/common/TwoStateHMM_PMD.o src/common/bsutils.o src/common/numerical_utils.o
ranlib libmethpipe.a
g++ -std=c++11  -O3    -o pmd src/analysis/pmd.o libmethpipe.a src/smithlab_cpp/libsmithlab_cpp.a -lgsl -lgslcblas -lz -lhts
source='../src/analysis/methcounts.cpp' object='src/analysis/methcounts.o' libtool=no \
DEPDIR=.deps depmode=none /bin/sh ../depcomp \
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I..  -I ../src/common -I ../src/smithlab_cpp   -O3  -c -o src/analysis/methcounts.o ../src/analysis/methcounts.cpp
g++ -std=c++11  -O3    -o methcounts src/analysis/methcounts.o libmethpipe.a src/smithlab_cpp/libsmithlab_cpp.a -lgsl -lgslcblas -lz -lhts
src/smithlab_cpp/libsmithlab_cpp.a(htslib_wrapper.o): In function `SAMReader::~SAMReader()':
htslib_wrapper.cpp:(.text+0x62): undefined reference to `sam_hdr_destroy'
collect2: error: ld returned 1 exit status
make[2]: *** [methcounts] Error 1
make[2]: Leaving directory `/root/methpipe-5.0.0/build'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/methpipe-5.0.0/build'
make: *** [all] Error 2
```
Sincerely appreciated!


[config.log](https://github.com/smithlabcode/methpipe/files/6922005/config.log)
