### ISSUE TITLE
"hmr_plant" absent

### ISSUE THREAD

**Issue by hchetia** [smithlabcode/methpipe#168]
Hi I was not able to build "hmr_plant" command to run with the test dataset. Is it missing from methpipe 4.1.1?

**Comment by terencewtli** [comment]
Hi,

Could you show me the documentation you're reading for methpipe? In our manual, we have a section that discusses plant methylation and which programs to use. I believe `hmr_plant` is referring to our `hyper_mr` program. However, the manual also mentions that you can find the blocks of hyper-methylated CpGs by inverting the methylation levels and running `hmr` on the sample.

**Comment by hchetia** [comment]
I was using the Readme.txt with the test dataset. Thanks for clearing that up. Hyper_mr works fine.

**Comment by terencewtli** [comment]
I see - I will edit that as well. Thanks for pointing that out!
