### ISSUE TITLE
to-mr cannot transform successfully instead of generating a null .mr file

### ISSUE THREAD

**Issue by xxzzwan** [smithlabcode/methpipe#173]
Hi, 
I met a problem with to-mr transforming bam file to .mr file on centos server.  I've set up all the environment the methpipe needs and installed methpipe successfully on the server. However when I used "`to-mr -o /path/name.mr -m bismark /path/mybam.bam`" command, it only run 3 minutes and wrote a null .mr file as output. 
`-rw-rw-r--. 1 zx zx           0 3月   4 23:27 lz1895n.mr`
My bam file path was correct and methpipe was also in my path. Insterestingly, when I used the same command and same bam file on my mac, it went well and generated a normal output. So why it cannot work on linux system or just centos? 
Hope somebody could help! Thanks a lot.

**Comment by xxzzwan** [comment]
Also, the g++ version on my centos server is 5.3.0. 
On my macos system, the g++ version shows as follows. 
```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by weishwu** [comment]
Did you figure it out? I'm having the same problem. There is no error message but the output *.mr file is empty.

**Comment by xxzzwan** [comment]
With version 4.1.1, no. I've downloaded the pre-release version 4.1.2 and used format_reads instead and it worked. Guess it's the bug inside the pipeline and they fixed. Hope it could help!

**Comment by guilhermesena1** [comment]
Thank you for reporting this. We are on the process of merging version  4.1.2 alpha to a full release in which the mr file format will no longer be necessary. I will close this issue since `to-mr` will no longer exist but we'll be happy to assist if other problems may arise with SAM outputs in the next releases.
