### ISSUE TITLE
Methcounts: problem with chrom order in mapped reads

### ISSUE THREAD

**Issue by shashwatsahay** [smithlabcode/methpipe#177]
I have been trying to run methcounts and I have divided the dataset chromosome wise for faster run computation on our cluster but every time I run the command I get the error "problem with chrom order in mapped reads" what I don't understand if there is not more than a single chromosome in the file being processed how can this be an error?

**Comment by terencewtli** [comment]
Hi, which version of Methpipe are you using? And would you be able to provide the files for me to test?

**Comment by shashwatsahay** [comment]
I am using the current version of methpipe. But I solved the issue by directly providing individual chromosome file instead of the whole genome

**Comment by hchetia** [comment]
Hi, I am not sure if I need to open a new issue or not, but my problem is the same.
I am getting the error "problem with chrom order in mapped reads" despite using the individual chromosome fasta files. I am using the v4.1.2-alpha version.
The steps prior to the methcount step were ran with the fullmoonlizard version.
Please help.
