### ISSUE TITLE
incompatible behavior between abismal and methpipe with chrom names

### ISSUE THREAD

**Issue by guilhermesena1** [smithlabcode/methpipe#183]
When abismal maps reads to a FASTA file with chromosome names containing spaces, it keeps only the first word in the chromosome name as its RNAME field. If  passed onto methpipe programs (e.g. `methcounts` or `bsrate`) and the same reference is used, the chromosome names in the SAM file, which contain only the first word, are not found in the reference.

Suggested fix: Change `read_fasta_file` in `smithlab_cpp` such that only the first word is used internally. Since both `bsrate` and `methcounts` use this function to read directories or files, it should cause consistent behavior.

**Comment by andrewdavidsmith** [comment]
Fixed with the `read_fasta_file_short_names` function instead.

**Comment by hchetia** [comment]
Could this issue also happen with bismark outputs? I get the error chromosome in SAM file not found in reference:chr1 when running methcounts command.
I am using methpipe v4.1.2 alpha.
The mr file was generated by converting the deduplicated bam file from bismark to sam using samtools and then converted to mr using format_reads.
