### ISSUE TITLE
meth to bed

### ISSUE THREAD

**Issue by hchetia** [smithlabcode/methpipe#187]
Hi,
I am trying to convert the meth file to bed for ultimately converting it to bigwigs.
The command provided in the manual  leads to an error-

awk: cmd. line:1: ’{print
awk: cmd. line:1: ^ invalid char '?' in expression

The command used is 
awk -v OFS="\t" ’{print $1, $2, $2+1, $4":"$6, $5, $3}’ CpG_sorted_start.meth CpG_sorted_start.bw

Best,
Hasna

**Comment by andrewdavidsmith** [comment]
Did you copy and paste into the terminal, or did you type it out?

**Comment by hchetia** [comment]
I was copy pasting earlier, when I kept getting the error. Tried typing the whole command and it worked. Why so?
