### ISSUE TITLE
average 5hmC and true 5mC level in regions of interest?

### ISSUE THREAD

**Issue by BenvanderVeer** [smithlabcode/methpipe#190]
Dear Methpipe Authors,

I have both oxBS and BS data and I estimated 5hmC and true 5mC levels using the MLML program.

I was wondering what the best way would be to calculate the 5hmC and 5mC levels over specific regions of interest (e.g. LINE elements, or promotors)? Should this be a weighted average by taking the total coverage of both oxBS + BS for each individual CpG, or average the methylation level of the individual CpGs? Or is there even another preferred method for this, or maybe it is not possible?

best, Ben

**Comment by andrewdavidsmith** [comment]
@BenvanderVeer I'm very happy to answer this question -- or at least give my personal opinion on it. But since this is somewhat outside technical details of the software development, it would be best if you contacted me directly by email.

**Comment by BenvanderVeer** [comment]
Thank you, I send an email this morning!
