### ISSUE TITLE
Using Nanopore data

### ISSUE THREAD

**Issue by Hannah1746** [smithlabcode/methpipe#192]
So I am trying to use this great pipeline on my Nanopore data. I finally got all the programs to install and work together. I am now having troubles with getting the data in the right format to use methpipe. My problem is with the program abismal:

https://github.com/smithlabcode/abismal/issues/5

I wanted see if there is another way of getting my data into the right format without using abismal since they seem to be very responsive on their github.

Thank you for you time and effort,
Hannah

**Comment by terencewtli** [comment]
Hi,

Is your current data in fastq format?

**Comment by guilhermesena1** [comment]
Closing because (1) this was discussed in the abismal repo and (2) inactivity, but feel free to reopen if this issue resurfaces
