### ISSUE TITLE
Install fatal error: gsl/gsl_sf_psi.h

### ISSUE THREAD

**Issue by avkermanov** [smithlabcode/methpipe#193]
As the similar issue was closed, I will open it here with the requested error code:

> make  all-recursive
make[1]: Entering directory '/home/akermanov/Packages/methpipe-4.1.1'
Making all in src/smithlab_cpp
make[2]: Entering directory '/home/akermanov/Packages/methpipe-4.1.1/src/smithlab_cpp'
make  all-am
make[3]: Entering directory '/home/akermanov/Packages/methpipe-4.1.1/src/smithlab_cpp'
make[3]: Leaving directory '/home/akermanov/Packages/methpipe-4.1.1/src/smithlab_cpp'
make[2]: Leaving directory '/home/akermanov/Packages/methpipe-4.1.1/src/smithlab_cpp'
make[2]: Entering directory '/home/akermanov/Packages/methpipe-4.1.1'
  CXX      src/common/BetaBin.o
src/common/BetaBin.cpp:31:10: fatal error: gsl/gsl_sf_psi.h: No such file or directory
 #include <gsl/gsl_sf_psi.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:1080: recipe for target 'src/common/BetaBin.o' failed
make[2]: *** [src/common/BetaBin.o] Error 1
make[2]: Leaving directory '/home/akermanov/Packages/methpipe-4.1.1'
Makefile:1102: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/akermanov/Packages/methpipe-4.1.1'
Makefile:622: recipe for target 'all' failed
make: *** [all] Error 2

_Originally posted by @avkermanov in https://github.com/smithlabcode/methpipe/issues/189#issuecomment-953014864_

**Comment by avkermanov** [comment]
Hi,

Thank you for suggestions. I have no sudo access on server, things are a bit tricky. I installed tools you noticed in a different folder and changed the PATH but it did not help. But installation of 5.0 version of methpipe ran smoothly. The only problem that I needed .mr files, as I designed scripts for them, but maybe it will be easier to modify my scripts then trying to force 4.1.1. version to install... 

Thank you!

**Comment by terencewtli** [comment]
Hi,

I see, let me check the methpipe 4.1.1 installation. The error you are running into is the one you posted in the original comment?

On my server, I created a `/usr/local/` directory somewhere and copied all of the files from the `gsl` and `htslib` installation files into the include/lib directories. And then put the following in my `~/.bashrc`:
```
export CPPFLAGS=-I/path/to/usr/local/include/:$CPPFLAGS
export LDFLAGS=-I/path/to/usr/local/lib/:$LDFLAGS
```
Then I run
```
./configure --prefix=`pwd`
```
This is a bit of a complicated solution, but seems to work for me... please let me know if this works or if you have any other solutions!
