### ISSUE TITLE
Installation issue htslib/sam.h

### ISSUE THREAD

**Issue by simiro** [smithlabcode/methpipe#194]
Hi, 
I've been trying to install methpipe on our hpc.
I have installed both GSL and HTSLIB.

I set prefix, LDFLAGS and CPPFLAGS during configuration and then `make` fives me the following error:

![image](https://user-images.githubusercontent.com/13441456/140762493-0b880a01-6582-44a9-81de-a870725b6ac7.png)

The file (sam.h) does exist.

Any pointer on getting this to run are much appreciated :)

**Comment by terencewtli** [comment]
Hi,

Could you show how you set LDFLAGS and CPPFLAGS and what's in those directories? As well as where you installed GSL and HTSLIB.

**Comment by andrewdavidsmith** [comment]
@simiro can you indicate which release you are using?

**Comment by simiro** [comment]
Thank you for your response.
I am trying to install methpipe version 5.0.

htslib is version 1.14
gsl is version 2.7 

CPPFLAGS='-I/psycl/u/siro/.local/include/' LDFLAGS='-L/psycl/u/siro/.local/lib/'

I've started over, installed gsl outside of anaconda, removed and reinstalled htslib. This has changed my error during the `make` step.

The error I get when trying to "make" methpipe 5.0 is as follows:
![image](https://user-images.githubusercontent.com/13441456/140896353-1fea3773-43d8-4f08-9f10-fb88927f5ab4.png)

Of note: I am actually able to install methpipe version 4.1.1 just fine with the current settings.
Obviously, I still would like to get the current version running.
