### ISSUE TITLE
hmr fails on sorted CpG's

### ISSUE THREAD

**Issue by cb4github** [smithlabcode/methpipe#195]
Dear All,

Using methpipe version 5.0.0, I'm getting the following result from hmr.

```
$ hmr -v -o CM1-1.hmr CM1-1.CpG.unique.sorted.formatted.bam.meth
[reading methylation levels]
error: input is not properly sorted: CM1-1.CpG.unique.sorted.formatted.bam.meth
```
I've tried explicitly sorting the CpG's output from symmetric-cpgs with the same result.
```
$ LC_ALL=C sort -k 1,1V -k 2,2n -o sorted.CM1-1.CpG.unique.sorted.formatted.bam.meth CM1-1.CpG.unique.sorted.formatted.bam.meth
$ diff sorted.CM1-1.CpG.unique.sorted.formatted.bam.meth CM1-1.CpG.unique.sorted.formatted.bam.meth
$ <diff is empty>
```
```
$ hmr -v -o CM1-1.hmr sorted.CM1-1.CpG.unique.sorted.formatted.bam.meth
[reading methylation levels]
error: input is not properly sorted: sorted.CM1-1.CpG.unique.sorted.formatted.bam.meth
```
Please advise, thanks.
Best,
CB

**Comment by guilhermesena1** [comment]
Hello,

Thank you for sharing the error. We are working on relaxing the condition that chromosome names need to be sorted alphabetically.

That said, can you try sorting it as follows and see if it fixes the issue? Thank you!

```
$ LC_ALL=C sort -k 1,1 -k 2,2n -k3,3 -o sorted.CM1-1.CpG.unique.sorted.formatted.bam.meth CM1-1.CpG.unique.sorted.formatted.bam.meth
```

**Comment by cb4github** [comment]
Dear @guilhermesena1,

Many thanks for your prompt reply. The hmr ran to completion with alphabetically sorted chromosomes.

For future benefit, it would help to update the [manual ](http://smithlabresearch.org/downloads/methpipe-manual.pdf) - dated July 26, 2021 at this typing - accordingly, thanks.

Best,
CB

**Comment by moqri** [comment]
Thanks for the hint. Is this now working with unsorted chromosomes?

**Comment by guilhermesena1** [comment]
It should be yes.

Also please note that all of our development of methpipe (including the past handling of this bug) is now on [dnmtools](https://github.com/smithlabcode/dnmtools)
