### ISSUE TITLE
NULL lines contained in .mr file which transformed from bam file

### ISSUE THREAD

**Issue by vanessayang0927** [smithlabcode/methpipe#197]
Hi, 
I installed version 4.1.1 successfully and prepared to computer methylation entropy. When I used "to-mr" command for transforming bam file to .mr file, it run without error and wrote a .mr file contained many NULL line. However I get the error information "bad line in MappedRead file: (NULL)	0	0	X	0	+	" in the next analysis (methstates). 

error read information in bam file: 
DP800003707TRL1C042R0210262385	147	chrM	14387	42	80M	=	14473	186	TAATTTTATTAAAATATTTATTAAGATTTTAATTTTTGATTTTTATGTTTTAGGATATTTTTTAATAGTTATTGTTGTAG	FFFFGFFFFGFFFFGFFFGFFFFFEFFFFFFFFFFFFF<FF;FFFFFFFFFFFFFFFFFFDFFFFFFFFFFFFFFFFFFF	NM:i:0	PG:Z:MarkDuplicates
DP800003707TRL1C042R0210262385	99	chrM	14473	42	100M	=	14387	-186	TAAAGATAATTATTATTTTTTTTAAATAAATTAAAAAAATTATTAAATTTATATAATTTTTTTTAAAATTTAGAATAATAATATATTTGATTATATTGTT	FGFFFFFFFFFFFEGGFFF9FFFGFFFGFGFFGFFFFGFEFGFG?;GGFEEGEFGDCFGFGGFAGFGGGCGDFFFAFBFGGEF?EG<GFAFFDF6GGFG=	NM:i:0	PG:Z:MarkDuplicates

**Comment by guilhermesena1** [comment]
Hello,

Thank you for reaching out about the problem. This issue was fixed on methpipe 5.0.0 (along with several other improvements in the pipeline). Would you be able to analyze your data with that instead? You would not need to use `to-mr` and can instead directly use the output of the mapper you are currently using.

**Comment by vanessayang0927** [comment]
Thank you for your reply. I  installed version 5.0.0 successfully and run without error. However, the entropu values of all CpG site were negative. Was this result normal?

**Comment by guilhermesena1** [comment]
Closing this to discuss on another issue. If there are still problems with the 5.0.0 version conversion this issue can be re-opened and we can discuss here.
