### ISSUE TITLE
format_reads for bwa-meth's SAM files

### ISSUE THREAD

**Issue by diegommcc** [smithlabcode/methpipe#215]
Hello, 

I'm working on a methyl ATAC-seq data generated using the experimental protocols described [here](https://www.nature.com/articles/s41596-021-00608-z). I've used bwa-meth to align the reads, but I've realized that methpipe now uses `format_reads` to merge paired-end mates into single-end entries. However, bwa-meth is not supported. I was wondering if there is any way to format bwa-meth BAM files in order to generate valid SAM files for methpipe. 

Thanks in advance.

**Comment by andrewdavidsmith** [comment]
@diegommcc sorry for the slow (or non) response. I don't think it's realistic at this time. Please comment again if you plan to keep using bwa-meth in the future. If enough people request this then it might be possible.
