### ISSUE TITLE
A new pipeline script for automated buildling library and merging replicates

### ISSUE THREAD

**Issue by mengzhou** [smithlabcode/methpipe#44]
@andrewdavidsmith suggested that we only need one script to do the job instead of having `library` and `biorep`. My opinion is that we write a python script which requires only mapped read files and experiment setup, including library and replicate information, and it does everything else.

But `amrfinder` will be a problem because it requires much more resources than other tools, and it might involve creating qsub jobs in the script which not all users need. Any thoughts?

**Comment by bdecato** [comment]
We recently removed the very deprecated pipeline scripts from methpipe and moved the automation this thread discusses to the MethBase repo.  Closing this issue.
