### ISSUE TITLE
Import of programs from pre-methpipe

### ISSUE THREAD

**Issue by andrewdavidsmith** [smithlabcode/methpipe#48]
Can people tell me which of the programs in pre-methpipe have already been fully imported into methpipe so I can remove them from my repo?

**Comment by bdecato** [comment]
I think the only two remaining to integrate are bsrate2 and roimethstat2.  We may benefit from rewriting bsrate to include analysis of bisulfite conversion along reads and potentially throw away reads that are low conversion.

**Comment by bdecato** [comment]
roimethstat2 imported.  Still need to implement bsrate2 and add option for merged-symmetric CpGs to levels2.

**Comment by bdecato** [comment]
@andrewdavidsmith I am testing bsrate2, and there are a few changes I was wondering what the motivation for was.

1) We no longer accumulate the "overhanging" bases and warn that a nonzero number of reads mapped to the very end of a chromosome.  Why was this removed?

2) bsrate2 has (potentially debug) output that prints the read counts to standard error.  Is this something that should be removed, or did you want to clean up the presentation and put it in an auxiliary file??

It looks like most changes are just formatting.  I removed bsrate2's identify_chromosomes function in favor of smithlab_cpp's and tested it: it produces identical output to the original.

**Comment by bdecato** [comment]
Per our conversation, it seems bsrate2 has previously been integrated/is not important to integrate.  All of the "2" programs in pre-methpipe have been incorporated now!
