### ISSUE TITLE
Add back support for single FASTA file as reference

### ISSUE THREAD

**Issue by mengzhou** [smithlabcode/methpipe#53]
Now only multiple FASTA by individual chromosomes is supported. I think the function is already there (`identify_and_read_chromosomes`).

**Comment by andrewdavidsmith** [comment]
@mengzhou can you please indicate the places where this functionality would be used? Likely it is something we want.

**Comment by mengzhou** [comment]
For example one uses the following command
`methcounts -c hg19.fa`
and `hg19.fa` includes all chromosomes. This is not recommended in our manual, but sometimes one might find it more convenient to use one single FASTA file (assuming the user knows what he is doing and no swapping issue).

**Comment by bdecato** [comment]
Is this still broken/a desirable piece of functionality to have?
