### ISSUE TITLE
Faster version of roimethstat that does not load entire methcounts file 

### ISSUE THREAD

**Issue by andrewdavidsmith** [smithlabcode/methpipe#62]
I wrote a version of roimethstat (currently in my adssrc repo) that does not need to load the entire methcounts output file, but instead searches for the appropriate range of CpG sites to load. It is much faster in most of the cases have encountered, but probably not, for example, if you are doing a million regions.

This should be tested by someone other than me, and then it can replace the current roimethstat program.

**Comment by bdecato** [comment]
I tested and replaced the original roimethstat program with this one.  As Andrew said above, it is much faster for a small set of regions but is around 3 fold slower on the entire set of hg19 refseq genes.  Not that big of a deal, and the memory usage went way down.
