### ISSUE TITLE
bsrate

### ISSUE THREAD

**Issue by acgtun** [smithlabcode/methpipe#64]
When I ran bsrate, one of the mapping results is following, but bsrate says there isn't chr1.

chr1	10019	10109	SRR1532538.162580060	0	+	AATTTTAATTTTAATTTTAATTTTAATTTTAATTTTAATTTTAATTTTAATTTTAATTTTAATTTTAATTTTAATTTTAATTTTAATTTA	___ceeeecgggcghhhhe^hhghhghhhhhfhhhhhhhhhhhefehhhhfhhbbcgghgfffghhhggfff`cgggdhfhdegggfdg`
could not find chrom: chr1

The mapping result is huge, 159Gb

**Comment by mengzhou** [comment]
Can you paste your command? Did you use -c for a directory containing
multiple chrN.fa files or -c to one .fa file which has multiple chromosomes?

Best regards,
Meng

**Comment by acgtun** [comment]
Hi, Meng,

Yes, I used -c option in the command. All commands are executed in this directory. 
/home/rcf-40/haifengc/panfs/bsm_test/bsmap/SRX666252
---------------------------------------------------------------------------------------------
bsrate -c ~/panfs/hg19_all.fa -o mp_merge.bsrate mp_merge.mr.dremove

methcounts -c ~/panfs/hg19_all.fa -o mp_merge.meth mp_merge.mr.dremove

levels -o mp_merge.levels mp_merge.meth

Thanks, Meng.

Best,
Haifeng

**Comment by mengzhou** [comment]
I think Saket has fixed this error. Can you update your methpipe and try
agian?

Best regards,
Meng

**Comment by saketkc** [comment]
Was fixed in 9b3e90857aabfe644e9cc2fb211cf5533303adf7

**Comment by acgtun** [comment]
Thanks Meng and Saket. I downloaded the latest one. It was fixed. Thanks a lot.
