### ISSUE TITLE
amrfinder unintended behavior

### ISSUE THREAD

**Issue by bdecato** [smithlabcode/methpipe#69]
amrfinder works by attempting to partition reads into two distinct sets, one primarily unmethylated and one primarily methylated.  the likelihood of this partitioned set is compared with the likelihood of the single-set to determine a region's allelic state.

With higher-coverage datasets, it becomes easier to partition the reads into two distinct sets due to the inherent randomness of methylation values and thus the likelihood increases relative to the single-allele model, but these sets have vastly different sizes.  For example, if a region has a 90% average methylation level and 100x coverage, we end up with 90 reads in the "methylated" set and 10 reads in the "unmethylated" set and accept it as an AMR, even though it is clearly not allelic.

We need to fix this, but ensure that whatever method we choose does not affect our ability to call AMRs in lower coverage samples.  For example, if we choose to accept only AMRs with 60/40 splits or more even, if we have a low coverage dataset where 7 reads are in one set and 3 are in the other, we would probably benefit from keeping it.

**Comment by andrewdavidsmith** [comment]
@mengzhou @bdecato Should this issue be closed?
