### ISSUE TITLE
Question regarding applicability to hemi-methylated bases

### ISSUE THREAD

**Issue by cviner** [smithlabcode/methpipe#72]
Section 2.4 of the MethPipe manual states that "[s]ince symmetric methylation is the common case for CpG methylation, we have *designed all of our analysis tools based on symmetric CpG sites*, which means each CpG pair generated by ```methcounts``` should be merged to one. [emphasis added]"

It is important for my analysis to be able to detect, even rare instances of, hemi-methylation across all genomic-contexts. While I am using the relevant MethPipe parameters to ensure an all-context analysis, are there aspects of MethPipe that are problematic if I elect to never assume symmetric methylation (i.e. if I never run ```symmetric-cpgs```)?

**Comment by bdecato** [comment]
The main reason for this assumption is to improve coverage per site, which directly impacts our ability to call hypomethylated regions (HMRs) in all cell types and partially methylated domains (PMDs) in cancer.  

If you use these downstream programs in the pipeline, the assumption of hemi-methylation does not matter in most contexts, and in the rare case where they are different in normal tissues, the methylation level of the unstranded CpG will reflect that accordingly.

One place I could see you using stranded CpGs in calling HMRs would be in replication timing bisulfite sequencing (do people do that??).  It would be possible to see HMRs on the nascent strand compared to the parent strand, if you ran HMR on each strand's CpGs separately.  Just keep in mind the HMM learns the parameters more accurately as coverage increases (and we typically only trust HMRs from datasets with >5 or 6x coverage).

**Comment by cviner** [comment]
I'm very glad to hear that. I realize it's common to pool over CpGs for better coverage and will indeed need to be careful that my coverage is sufficient without doing so. I'm actually only using your pipeline up to ```methcounts``` → ```mlml```, and am not investigating HMRs using your HMM (although I might at some point, so these considerations, especially your coverage heuristic, are quite useful). I actually think I have heard of groups conducting some strand-sensitive replication-timing WGBS experiments (a neat concept!), but my data does not pertain to that. I'm really "just" trying to obtain consistent, single-base resolution, 5mC and 5hmC all-context, strand-sensitive, estimations; fortunately this pipeline seems to do a great job of that.

Thanks for the quick reply and for this great news!
