### ISSUE TITLE
merge-methcounts "inconsistent context" errors

### ISSUE THREAD

**Issue by cviner** [smithlabcode/methpipe#73]
I am running ```merge-methcounts``` to merge the output from ```methcounts``` (which was run for all genomic contexts, i.e. without ```-n```). However, I receive the fatal error: "inconsistent context" for all of my merge attempts.

One example line of my input file for which this error occurred is as follows:

```
chr1	3000102	-	CHHx	0	0
```

Another file had the error at the following line:
```
chr1	3000417	-	CXGx	0	1
```

It looks like this is caused by the terminal "x" in the genomic context column. What does this "x" mean and how can I resolve this problem?

**Comment by mengzhou** [comment]
It looks like your input files have different number of lines, and then `merge-methcounts` is trying to merge two different sites into one. Can you check the total number of lines of your individual input files?

**Comment by andrewdavidsmith** [comment]
Try to forward these questions to the google group for methpipe, and answer it there. Unless we are actually talking about parts of the code (which might happen eventually for this issue).

**Comment by cviner** [comment]
@mengzhou:

I am re-computing another run of ```methcounts``` → ```merge-methcounts``` and will be able to ensure that I can reproduce this error and check the total number of lines of the ```methcounts``` output files (I wasn't storing them all for these tests due to their size). I'll let you know once that is done.

Just to clarify, since I never use ```-n``` and always use the same directory path to my copy of mm9, the expected behaviour of ```methcounts``` is to always have a single line for every cytosine in the genome, correct?

What does the terminal "x" in the context string mean?

I should mention that I am using MethPipe 3.3 and not the latest development version.

Thanks for your continued assistance.

@andrewdavidsmith: Okay; I'll be sure to do that instead for any future questions, and migrate here if/when discussions of code arise.

**Comment by andrewdavidsmith** [comment]
Thanks @cviner I understand this particular case might easily end up being a bug and then appropriately discussed here -- all your input is very much appreciated.

**Comment by cviner** [comment]
@andrewdavidsmith: I appreciate how active your lab is in developing and supporting this valuable piece of software!

@mengzhou: I have been able to reproduce this error. The current test run was comprised of an attempt to merge 4 files. There does indeed appear to be an issue of files of inconsistent lengths, but I'm not certain that was the proximal cause of the error, and may instead be symptomatic of another problem or purely coincidental. The error occurs for the file that is of a lesser length from the other three, but this may be incidental. Three of the output ```methcounts``` files were the expected 25 GB in size, but one was only 6.6 GB. Surprisingly, all four files actually differ in size. I provide below (formatted) output from ```lc_approx -v```:

File | File Size | Chunk Size | # of chunks | Total Sample | Est. # of lines
------------ | ------------- | ------------- | ------------- | ------------- | -------------
1 | 25098.5MB | 102KB | 100 | 9.99994MB | **1 069 611 266**
2 | 25110.7MB | 102KB | 100 | 9.99994MB | **1 069 628 812**
3 | 25110.7MB | 102KB | 100 | 9.99994MB | **1 069 612 480**
4 | 6686.41MB | 102KB | 100 | 9.99994MB | **280 860 384**

Despite this, the first three files are indeed all of the same length (```wc -l``` reports a line count of
1 068 446 432 for all three). As I discuss below, the difference in the file sizes of the first three can be accounted for by their differing number of terminal "x" genomic context string markers of selected loci. Accordingly, the differing ```lc_approx``` line counts for those three files are artifacts of the aggregate presence or absence of context-terminal "x"'s.

The files all appear to start with the same cytosine loci, as expected. The error actually occurs before the files differ in terms of the cytosine loci reported therein. The error occurs on line 30 of file 4. The loci reported for all files, including the genomic context string for each locus, is consistent until line 30 (only the first four ```methcounts``` columns, which are expected to always be identical for a particular sample and genome, are included):

File(s) | Line # | Chrom. | Pos. | Strand | Context
------------ | ------------- | ------------- | ------------- | ------------- | -------------
1–3 | 30 | chr1 | 3000102 | - | CHH
4 | 30 | chr1 | 3000102 | - | CHH**x**

The problem appears to be caused by the terminal "x" in the context string of only one of the files.

As expected, the files themselves (excepting the fourth file) are identical in terms of the order and content of their individual cytosine loci (i.e. the first three columns of the 4 ```methcounts``` output files do not differ). The fourth file appears to have been truncated at the end of chromosome 13 (i.e. it completed chr1, and chr10–13, but did not make it onto chr14; the file's final entry pertains to a CCG-context locus at chr13:120284311). Despite this apparent truncation, ```methcounts``` did not output any warnings or errors and did detect the correct number (22) of chromosomes.

The issue (?) of terminal "x"'s appearing in a single file's context string occurs at *many* loci. It happens that the first context-terminal "x" occurred on line 30 of file 4, which was also the shortest file (but I have insufficient evidence to infer any causality). Another (randomly selected) example, in which a terminal "x" appears only in the context string for that locus of file 1 occurs at line 12 249 485:

File(s) | Line # | Chrom. | Pos. | Strand | Context
------------ | ------------- | ------------- | ------------- | ------------- | -------------
1 | 12 249 485 | chr1 | 34240383 | - | CXG**x**
2–4 | 12 249 485 | chr1 | 3000102 | - | CXG

A quick inspection of the loci and genomic contexts for which these terminal "x"'s appear does not reveal any clear patterns. They seem to occur for any context (i.e. all of CpGx, CCGx, CXGx, and CHHx occur frequently) and there is no obvious strand bias. I provide below the aggregate frequency of these terminal "x"'s across the four test files:

File | Number of loci with a context-terminal "x"
------------ | -------------
1 | 473 585
2 | 650 307
3 | 630 796
4 | 169 683

Based upon my (cursory) inspection of [```methcounts.cpp```](https://github.com/smithlabcode/methpipe/blob/master/src/analysis/methcounts.cpp), it looks like the "x"'s are indicative of a mutation, i.e. that the observed bisulfite conversion was putatively caused by a SNP and is not an actual conversion event [[```methcounts.cpp```, lines 177]](https://github.com/smithlabcode/methpipe/blob/master/src/analysis/methcounts.cpp#L177). However, the four files I am merging are each individual lanes, from a single library (i.e. they are effectively technical replicates). Each was aligned, using Bismark, to NCBI37/mm9. It is not clear to me how the SNP inferences could differ so drastically between them (I realize some differences are to be expected, due to technical variation in the sequencing between lanes, but this level of inter-lane variation seems quite high). I also don't understand why the annotation of putative mutations appears to cause downstream "inconsistent context" errors in ```merge-methcounts``` (it seems like a regression in ```merge-methcounts```, but I can't seem to find its cause and cannot even locate where exactly in the source code the error is being generated).

I hope that this helps to narrow down the error for you. I'm open to any suggestions for further tests I can run to help do so.

**Comment by egor-dolzhenko** [comment]
@cviner, it looks like the problem with merging mutated and non-mutated sites has been fixed in the development version (commit aaa861d12b7d76008b3c9b375d80fa3d1e693476). Could you please try the development version of `merge-methcounts`?

**Comment by cviner** [comment]
@egor-dolzhenko: I appreciate the suggestion. I had to checkout revision 3655360, since I encountered a compilation error upon checking out the current head, I believe due to [a minor error introduced](https://github.com/smithlabcode/methpipe/commit/fd13264b3310102771fe28d886326b22610037bc#commitcomment-12306201) in fd13264.

I have now tested ```merge-methcounts```, on the development version and it does indeed work!

I will still need to investigate why the various lanes of a single library have such differing inferred mutation counts and why my fourth file's ```methcounts``` run got silently truncated, but the main problem here is now resolved.

Thanks!

**Comment by egor-dolzhenko** [comment]
@cviner, I am glad to hear that the newer `merge-methcounts` worked. 

I am not sure what might be causing your `methcounts` file to get truncated. I have processed quite a few data sets with `methpipe` and never had this issue. I suppose one (unlikely) reason that could cause this is if an input file suddenly becomes unavailable (due to being moved or compressed) while `methcounts` is still running.

Does the mapped-read file have any reads that span a region past the truncation point? If so, you could try pulling out those reads and re-running `methcounts` on the resulting read file to see if it works. This could help us to pinpoint the problem.

**Comment by cviner** [comment]
The former possibility had occurred to me, but I've reproduced the truncation of the same file on one other occasion and also found no errors (e.g. file not found, broken pipe, etc.).

Your latter point seems like a good way to approach this, but the only way for a read to span past the truncation point in this case would be if (part of it) it aligned "off-of" part of the mm9 assembly, i.e. was soft-clipped from a read which would otherwise extend past the end of chr13 (since that's where the truncation occurs). It's my understanding that Bowtie 2 would not permit such an alignment (i.e. it would discard any reads for which an (additional) truncation would be necessary or it would move the read to obtain an alignment of lesser sequence similarity, since it aligns reads end-to-end by default, and I did not enable ```--local``` to allow soft-clipping, and I don't believe that Bismark enables that either).

Nonetheless, I used [BEDTools' ```window```](http://bedtools.readthedocs.org/en/latest/content/tools/window.html) to query the corresponding BAM file for reads 1 kb up- and down-stream of the final chr13 position (120284311 (0-based; 120284312 in the BAM file)), which is coincidentally a cytosine, and was accordingly also the final entry of the truncated ```methcounts``` output file.

As expected, the BAM file did not have a read which spanned beyond the end of (mm9) chromosome 13, but did have a read which aligns "exactly" (with a CIGAR string of "100M", although it does have an annotated edit distance of 22 and a map quality of 42) to the end of that chromosome, at its very last, cytosine, base.

**Comment by mengzhou** [comment]
can you paste that specific read here?

**Comment by egor-dolzhenko** [comment]
It might be useful to include reads from other chromosomes that "follow" chr13 (that is the reads that `methcounts` did not process). The idea is to get the read(s) that `methcounts` input when it decided to quit.

**Comment by cviner** [comment]
@egor-dolzhenko I looked for any reads aligning within the first 1 kb of chr14 (as expected, there were none), but will expand that window to find its first read.

**Comment by cviner** [comment]
The first chr14-mapped read occurs at position 3000017 (in the one-based coordinate system). The read is mapped in its proper pair, of which it is the first and on the positive strand.

It occurs on line 1 953 285 of the (read name-sorted) BAM file. The final mapped, previously discussed, chromosome 13 read occurs on line 38 130 915 of the BAM file.

I am currently attempting to bypass ```merge-methcounts``` by directly concatenating ```to-mr``` outputs, prior to running ```duplicate-remover``` → ```methcounts``` (although I had to do this anyway for a number of files, since I need to remove the duplicates for each set of concatenated sequencing lanes). However, I am running into a similar problem, wherein ```mlml``` fails:

```
mlml: mlml.cpp:522: int main(int, const char**): Assertion `f_chr == s_chr && f_pos == s_pos' failed.
/sge/middle_earth/spool/n28vm1/job_scripts/2095479: line 1:  4745 Aborted                 (core dumped) 
```

This may be caused by the same issue, but I have now reproduced the upstream problem for a few sets of analyses (i.e. for ```methcounts``` run upon other data from various (directly) concatenated ```to-mr``` outputs). Specifically, the number of ```methcounts``` output lines (as assessed by ```wc -l```) differ from each-other, which is unexpected given that they all pertain to the exact same copy of the mm9 assembly and should (as far as I understand it) have a single line pertaining to each cytosine in mm9.

The ```methcounts``` outputs differ, and accordingly resulted in my obtaining the above ```mlml``` error for two out of four ```mlml``` runs (the other two, run with ```methcounts``` outputs with the same number of lines, succeeded). Interestingly, there are only two different numbers of lines for the ```methcounts``` output files:
1 092 737 591 lines or 1 092 736 040 lines. Half of the eight ```methcounts``` output files have one size, while the other half have the other. There are no perfect correlations to the sex of the sample, the lane or replicate number of the sample, nor conventional versus oxidative bisulfite sequencing. I am looking into this further, by attempting to locate the (presumably common) 1551 specific loci which appear to be missing in half of the files.

I am not certain that this is the same as the truncation issue, since the files do all start and end with the exact same loci and context strings, but it seems conceivable that this has the same cause (presumably specific types of reads causing problems). Perhaps the issue is not simply ```methcounts``` quitting as we expected, but rather some sort of set of reads which cause ```methcounts``` to cease to output data pertaining to covered cytosine bases? I am quite baffled by ```methcounts``` not returning exactly one line per cytosine base. Have I perhaps misinterpreted its expected behaviour? Are there specific instances (outside of the use of the ```-n``` / ```-cpg-only``` parameter) in which it is intended to completely omit a cytosine position?

**Comment by cviner** [comment]
I aligned my data to the UCSC mm9 release, including the not-fully-placed or unplaced ("random") contigs. This might be causing difficulties for ```methcounts``` or perhaps it is coincidental and it happened that the reads causing problems occurred at a boundary which implicated a "random" chromosome. As depicted below, the issue appears to occur in the transition from chromosome 16 to 17, and have been caused by the absence of chr16_random.

Chromosome and position for the region of the ```methcounts``` file in which the first difference (WRT the first four columns only) occurs for a single (lane-merged, oxBS-Seq) run:

Chrom. | Position
------------ | -------------
chr16 | 98319144
chr16 | 98319149
chr16_random | 0
chr16_random | 1
chr16_random | 2
chr16_random | 3

Chromosome and position ```methcounts``` columns for the same line numbers in another (lane-merged, BS-Seq; same biological sample as previous) run:

Chrom. | Position
------------ | -------------
chr16 | 98319144
chr16 | 98319149
chr17 | 3000000
chr17 | 3000002
chr17 | 3000004
chr17 | 3000005

However, the two ```methcounts``` output files have identical loci for the transition from chromosome 13 to its unplaced contig set, with both files having:

Chrom. | Position
------------ | -------------
chr13 | 120284305
chr13 | 120284306
chr13 | 120284311
chr13_random | 0
chr13_random | 3
chr13_random | 4


I don't have the exact ```to-mr``` merged output that was used to run ```methcounts```, since (for this dataset), while I stored the ```to-mr``` output per lane, I simply concatenated the lanes of a single library and piped it through ```duplicate-remover``` → ```methcounts```.

I will work on re-constructing the respective merged and de-duplicated ```to-mr``` formatted reads that were input into ```methcounts``` for the reads near the chromosome 16/17 boundary. I would nonetheless appreciate an explanation as to how and why the reads themselves could influence which loci are surveyed by ```methcounts```, since I expect it to always still output a line for cytosines without any read coverage (and it does indeed always do so from what I can tell).

**Comment by cviner** [comment]
I am still not sure why chr16_random is only in one of the two aforementioned files. As far as I can tell there is only a single read that aligned to that chromosome and is present in the de-duplicated and merged to-mr output. The merged file that the chr16_random read is present in is the one which contained chr16_random data from ```methcounts```, while the other did not.

Is it possible that chromosomes without any reads input into  ```methcounts``` are being skipped, despite being present in the reference provided to ```methcounts```?

**Comment by cviner** [comment]
I have now confirmed that the 1551 additional lines appearing in half of my ```methcounts``` output files are all from chr16_random, which is missing in the other half of the files. This occurs despite both sets of files using the same reference genome. The files with these additional chr16_random lines are exactly and only those with non-zero chr16_random-aligned reads in their respective ```to-mr``` outputs. Despite variable numbers of chr16_random-aligned reads (ranging from 1-3 per merged dataset), the presence of a single such alignment was sufficient for all (1551) chr16_random cytosine loci to be output by ```methcounts``` and the converse held for the absence of any such alignments.

Accordingly, it appears that ```methcounts``` does, at least in some instances, suppress outputs for loci which have zero coverage for its entire containing chromosome. Given that this occurred across multiple files, each with quite different chr16_random-aligned reads, it (tentatively) appears to be independent of the actual alignments themselves.

**Comment by bdecato** [comment]
Hi Coby,

It looks like you're right: there is a line in methcounts.cpp (line 328)
that omits chromosomes if their coverage is zero at every site.

I think this is the wrong approach because it is inconsistent: if we omit
uncovered sites, we should do it for all uncovered sites, not just a
chromosome that is completely uncovered in the name of saving space when it
causes downstream problems merging.  You can fix this yourself by
commenting or removing the line or by pulling my latest commit.

Sorry about all the trouble!!

Ben



On Tue, Jul 28, 2015 at 4:18 PM, Coby Viner <notifications@github.com>
wrote:

> I have now confirmed that the 1551 additional lines appearing in half of
> my methcounts output files are all from chr16_random, which is missing in
> the other half of the files. This occurs despite both sets of files using
> the same reference genome. The files with these additional chr16_random
> lines are exactly and only those with non-zero chr16_random-aligned reads
> in their respective to-mr outputs. Despite variable numbers of
> chr16_random-aligned reads (ranging from 1-3 per merged dataset), the
> presence of a single such alignment was sufficient for all (1551)
> chr16_random cytosine loci to be output by methcounts and the converse
> held for the absence of any such alignments.
>
> Accordingly, it appears that methcounts does, at least in some instances,
> suppress outputs for loci which have zero coverage for its entire
> containing chromosome. Given that this occurred across multiple files, each
> with quite different chr16_random-aligned reads, it (tentatively) appears
> to be independent of the actual alignments themselves.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smithlabcode/methpipe/issues/73#issuecomment-125779442>
> .
>



-- 
-- 
Benjamin Decato
PhD Student
Computational Biology Section,
Department of Biological Sciences,
University of Southern California
1050 Childs Way, RRI 408A
Los Angeles, CA 90089-2910

**Comment by cviner** [comment]
Thanks, Ben!!

I seem to still be encountering the same assertion error with ```mlml``` in some cases, even when I ensure that both ```methcounts``` files have identical (and sorted) loci. I'm investigating that now.

**Comment by cviner** [comment]
The ```mlml``` problem is now solved. The only remaining issue ended up being a technical problem on my end.

Thank you all for your assistance!
