### ISSUE TITLE
Reporting "effective genome size" in the output of HMR program

### ISSUE THREAD

**Issue by andrewdavidsmith** [smithlabcode/methpipe#74]
The HMR program should report the size of the genome that is contained in "non-desert" regions of the genome. A related issue is whether to eliminate non-desert intervals that are too small. The cutoff of 1 CpG being "too small" is sensible, as we would never want to call an isolated CpG site as an HMR (at least the way we currently understand the HMRs as intervals). This second issue arises when we try to compute the size of the non-desert genome, as single-CpG sites might be treated as having size 0 if we measure interval size as the difference between the start of the last CpG site and the start of the first one.

**Comment by andrewdavidsmith** [comment]
Yes, this is definitely a good idea.

**Comment by bdecato** [comment]
> The HMR program should report the size of the genome that is contained in "non-desert" regions of the genome.

Should this report be in the --verbose output or as a separate statistics file?  Is it useful to include a stats output file for each program we have in ``methpipe``?  What should be different in Jenny, Liz, and my implementations of specific flavors of ``hmr``?

>A related issue is whether to eliminate non-desert intervals that are too small. The cutoff of 1 CpG being "too small" is sensible, as we would never want to call an isolated CpG site as an HMR (at least the way we currently understand the HMRs as intervals).

If we eliminate non-desert intervals, then I worry we're just introducing another cutoff where the FDR correction already handles the isolated-CpG-as-an-HMR issue.  Is the motivation here to heuristically save computation time or is there a statistical method to determine this cutoff?

>This second issue arises when we try to compute the size of the non-desert genome, as single-CpG sites might be treated as having size 0 if we measure interval size as the difference between the start of the last CpG site and the start of the first one."

I have a program, ``oceans``, that reports the size of each contiguously covered and uncovered region.  If we are consistent it isn't hard to make the one-CpG island have a size of 1.  The bigger problem is that it currently ignores the bases between the last uncovered CpG and first covered CpG.  Which do those bases belong to, the ocean or the island?

We can add this to the topics to discuss next Tuesday at 11.

**Comment by andrewdavidsmith** [comment]
I think the verbose output might be worth reconsidering in general. Stats are good things to have.

**Comment by bdecato** [comment]
Verbose output now includes an "EFFECTIVE GENOME PROPORTION" that gives the proportion of the genome in basepairs that exists in non-desert regions.
