### ISSUE TITLE
the number of lines for the methcounts output file is not consistent in the same genome

### ISSUE THREAD

**Issue by acgtun** [smithlabcode/methpipe#76]
I ran the methcounts on two datasets using the same genome (hg19). The number of lines for the two output files are different. One is 1186217236, and the other is 1186291952.

**Comment by bdecato** [comment]
This is an ongoing problem in methcounts -- I recently fixed an issue where if a chromosome was not covered at all, it was not printed.  Tomorrow I will reproduce this bug with my own copy of methpipe and hopefully figure out what is causing the difference.

**Comment by acgtun** [comment]
Thanks @bdecato

**Comment by acgtun** [comment]
when I only considered the 25 chromosomes, I got the same number.

**Comment by mengzhou** [comment]
By default we should only use those chromosomes: chr1-22, X, Y and M, not those chr_random/chr_Un. I think it should be mentioned somewhere in the Wiki?

Best regards,
Meng

**Comment by acgtun** [comment]
Thanks, @mengzhou .

Before the size of methcounts output file was about 28 Gb, but now it's only 4.8 Gb. Is that normal? Thanks.

**Comment by mengzhou** [comment]
4.8G sounds weird to me. It should be either around 21G for all cytosines,
or about 800M if you use -n for only CpGs.

Best regards,
Meng

**Comment by acgtun** [comment]
I didn't use -n option. It should be more than 20 Gb.

**Comment by bdecato** [comment]
Is the file truncated/does it include every chromosome in the directory?
Definitely sounds weird.

On Mon, Sep 21, 2015 at 8:59 PM, Haifeng Chen <notifications@github.com>
wrote:

> I didn't use -n option. It should be more than 20 Gb.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smithlabcode/methpipe/issues/76#issuecomment-142173741>
> .
>



-- 
-- 
Benjamin Decato
PhD Student
Computational Biology Section,
Department of Biological Sciences,
University of Southern California
1050 Childs Way, RRI 408A
Los Angeles, CA 90089-2910

**Comment by acgtun** [comment]
@bdecato You are right. I just checked. It was truncated. It doesn't contain all the 25 chromosomes. However, when I ran the methcounts, I included all of them.

**Comment by acgtun** [comment]
When I mapped the reads, I used the 93 chromosomes in hg19. Then I used 93 chromosomes to run methcounts, but I got different number of lines of output files. After that, I ran methcounts on the 25 chromosomes,  the results were truncated because when methcounts cannot find one of the chromosomes, it stooped.

**Comment by andrewdavidsmith** [comment]
Was any error printed to the screen when it stopped?

**Comment by bdecato** [comment]
Yes.  It may be better to print a warning and ignore all reads matching
that chromosome.

On Tue, Sep 22, 2015 at 10:20 AM, Andrew Smith <notifications@github.com>
wrote:

> Was any error printed to the screen when it stopped?
>
> On Tue, Sep 22, 2015 at 10:03 AM, Haifeng Chen <notifications@github.com>
> wrote:
>
> > When I mapped the reads, I used the 93 chromosomes in hg19. Then I used
> 93
> > chromosomes to run methcounts, but I got different number of lines of
> > output files. After that, I ran methcounts on the 25 chromosomes, the
> > results were truncated because when methcounts cannot find one of the
> > chromosomes, it stooped.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/smithlabcode/methpipe/issues/76#issuecomment-142349556>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smithlabcode/methpipe/issues/76#issuecomment-142354429>
> .
>



-- 
-- 
Benjamin Decato
PhD Student
Computational Biology Section,
Department of Biological Sciences,
University of Southern California
1050 Childs Way, RRI 408A
Los Angeles, CA 90089-2910

**Comment by acgtun** [comment]
@andrewdavidsmith It said one of the chromsomes was not found.

**Comment by bdecato** [comment]
The fix for this bug was in implemented in commit a66a92e.  Please update to the latest version of methpipe and run again with all chromosomes present to get the same line numbers for each sample.

**Comment by acgtun** [comment]
Hi, @bdecato , I think this line should be also removed. https://github.com/smithlabcode/methpipe/blob/a66a92e367faf5c0d2b5e1fc0c9d78d727987f1f/src/analysis/methcounts.cpp#L312

Otherwise, we cannot get the same line numbers.

**Comment by acgtun** [comment]
@bdecato  I am sorry. When count is empty, no matter you delete or not, it won't output anything. So  commit a66a92e will not change the output file.

**Comment by acgtun** [comment]
I guess the number of lines are different on two datasets because some of the sites are not covered by the mapped reads.

code is here https://github.com/smithlabcode/methpipe/blob/a66a92e367faf5c0d2b5e1fc0c9d78d727987f1f/src/analysis/methcounts.cpp#L328

**Comment by andrewdavidsmith** [comment]
No. That doesn't determine what gets output.

I think we have always had a mode to output the full set of sites for the chromosomes loaded, whether covered or not.

**Comment by acgtun** [comment]
@andrewdavidsmith  it's here 
for (size_t i = 0; i < counts.size(); ++i) {

when chromosome end positions are not covered by any mapped reads, they are  not in the output file. 

https://github.com/smithlabcode/methpipe/blob/a66a92e367faf5c0d2b5e1fc0c9d78d727987f1f/src/analysis/methcounts.cpp#L198

**Comment by acgtun** [comment]
@andrewdavidsmith  I think you are right. since the size of counts is the same to chrom.size()

 counts.resize(chrom.size());
https://github.com/smithlabcode/methpipe/blob/master/src/analysis/methcounts.cpp#L324
