### ISSUE TITLE
CpG-only mode for methcounts

### ISSUE THREAD

**Issue by andrewdavidsmith** [smithlabcode/methpipe#79]
Should this mode output the symmetric form of the counts? It seems like the usefulness of this mode is to provide a file that we have traditionally worked with for understanding CpG methylation.

**Comment by mengzhou** [comment]
We have `symmetric-cpg` for this functionality. I don't quite remember but I think the reason `-n` keeps both CpG sites is to enable checking asymmetric methylation conveniently.
