### ISSUE TITLE
methcounts doesn't work on one dataset

### ISSUE THREAD

**Issue by acgtun** [smithlabcode/methpipe#80]
On one dataset, methcounts doesn't work well. @egor-dolzhenko found out that the chromosome name is different to the fasta file name. However, after changing them to the same name, methcounts still doesn't work well.

**Comment by bdecato** [comment]
This issue needs to be more specific.  What do you mean by "doesn't work well?"  Could you give a description of the input and output?

**Comment by acgtun** [comment]
@bdecato the input is the output of duplicate-remover, the output is empty.

**Comment by egor-dolzhenko** [comment]
It actually worked for me after I renamed the files; @acgtun, let's compare what we did.
