### ISSUE TITLE
merge-methcounts running slow

### ISSUE THREAD

**Issue by mengzhou** [smithlabcode/methpipe#81]
I didn't do solid tests, but I do feel that it is running much slower than it used to be. Maybe the new functionality needs to be optimized.

**Comment by andrewdavidsmith** [comment]
I looked into this on Friday. @bdecato also mentioned the slowness, but I responded based on some bad information. The algorithm inside merge-methcounts is not optimal. There is also much copying of heavy objects. @bdecato had the suggestion of two modes. This should be trivial to implement. Maybe this issue should be revised.

**Comment by andrewdavidsmith** [comment]
Closing this issue, as `merge-methcounts` has been rewritten since.
