### ISSUE TITLE
roimethstat potentially will miss to count site(s)

### ISSUE THREAD

**Issue by mengzhou** [smithlabcode/methpipe#85]
In this fix f63954e @sarahsma reported a bug when `roimethstat` is in binary search mode, the location function sometimes locates the file pointer to a CpG site which is before the query region start position. And then the counting while loop will reject to continue and return a false -nan value. My fix added another while loop to move the file pointer forward in this case.

However I'm not sure if it is possible that the file pointer can be located one site after the starting position, which cannot be detected and will cause the counting loop to miss the starting site. Maybe more test is needed? Or @andrewdavidsmith can tell if the locating function will only bias towards one direction and this case will not happen?

**Comment by andrewdavidsmith** [comment]
I just made an update that should fix this. @sarahsma or @mengzhou should check.

**Comment by mengzhou** [comment]
I think now it's working correctly.
