### ISSUE TITLE
Shared functions in `levels`, `roimethstat`, and new binning program

### ISSUE THREAD

**Issue by bdecato** [smithlabcode/methpipe#86]
`levels`, `roimethstat`, and the new binning program designed to query the correlation between various methylome features and CpG density that is coming to adssrc have a lot of shared functions.

At some point soon we should consider refactoring these programs to include the shared utilities as part of smithlab_cpp.

**Comment by andrewdavidsmith** [comment]
@bdecato can you make this a bit more specific?
