### ISSUE TITLE
Bus errors with `symmetric-cpgs`

### ISSUE THREAD

**Issue by bdecato** [smithlabcode/methpipe#87]
Getting bus errors and running for a long time when I run symmetric-cpgs on a subset of my files.  What about this program is hard on the hardware?

My understanding of a bus error is when you try to access a memory location that does not physically exist (maybe by offsetting your addresses somehow).  How could such a simple program be causing a problem like this?

Ben

**Comment by andrewdavidsmith** [comment]
Bus errors often come from using a "slightly wrong" binary, or recompiling a program while it is being run if it runs for a long time and somehow gets read off disk again. In the "slightly wrong" case, one example is if some of the dynamically linked libraries are not identical to the ones present when the program was compiled.

**Comment by andrewdavidsmith** [comment]
Should this issue be closed? Can the issue be reproduced reliably?

**Comment by bdecato** [comment]
I'm not seeing any problem on my existing methcounts files.  It's entirely possible I was just being stupid.  Closing until I see it pop up in a reproducible case.
