### ISSUE TITLE
"bad output file" on methcounts

### ISSUE THREAD

**Issue by guilhermesena** [smithlabcode/methpipe#88]
I was trying to run methcounts following the manual instructions and to my surprise every filename I set for my output file ("-o" option) returned a "bad output name". I checked the code to see why that was happening and noticed there's a function in smithlab_cpp/smithlab_os.cpp (line 544) that uses the unistd.h's "access" function to check **whether my .meth output filename exists**, which it obviously didn't because I had never run the code. When I first created an empty file with the name of my .meth output and then ran it everything worked with no problem. Is this a design choice for any reason? None of the other binaries seem to work that way and this is not specified in the manual.

**Comment by bdecato** [comment]
Can you check to see if this issue was fixed with my recent commit? We had
a similar bug last week. Thanks!!

**Comment by andrewdavidsmith** [comment]
This is the same issue as we discussed Thursday at the meeting. For now just remove the check. I'll fix it when I can.

**Comment by andrewdavidsmith** [comment]
Should this issue be closed? Maybe we need to make a different issue related to checking the output file is valid?

**Comment by mengzhou** [comment]
I think it has been fixed. For the output validation, we can open a new issue to discuss it.

**Comment by bdecato** [comment]
Making a new issue for output validation.
