### ISSUE TITLE
Design an uniform class named MSite for methylation sites

### ISSUE THREAD

**Issue by tushiqi** [smithlabcode/methpipe#93]
Since multiple programs in methpipe have defined its own "struct" to represent a genomic methylation site, it may be a good idea to design a uniform class that provides a comprehensive set of operations so that each program could simply invoke the tool. There is an initial definition of MSite in src/common/MethpipeSite.hpp. Any suggestion about adding to its functionality and/or modifying its definition structure is welcome!

**Comment by andrewdavidsmith** [comment]
Done.
