### ISSUE TITLE
make_table in the documentation

### ISSUE THREAD

**Issue by avilella** [smithlabcode/methpipe#98]
Dears,

I am trying to follow the section of the documentation for radmeth, and there is a mention of a `make_table` tool that I cannot find anywhere.

It then asks to run `merge-methcounts -t` but I cannot see a -t flag in the source code for merge-methcounts. Any ideas? See attached screenshot.

<img width="807" alt="screen shot 2016-10-20 at 16 43 45" src="https://cloud.githubusercontent.com/assets/158007/19567067/6772c1ce-96e4-11e6-96f2-c208c8954ac5.png">

**Comment by jqujqu** [comment]
I think `make_table`  is be a typo, it should be `merge-methcounts`

`merge-methcounts` has the option `-t` here
https://github.com/smithlabcode/methpipe/blob/master/src/utils/merge-methcounts.cpp#L229

**Comment by avilella** [comment]
Thanks, I found the option in the head master branch now after doing a git pull.
